///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

// Order dependent includes
#include <wx/stattext.h>
#include <wx/generic/stattextg.h>

#include <wx/bitmap.h>
#include <wx/colour.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/settings.h>
#include <wx/statbmp.h>
#include <wx/statline.h>

class about : public wxDialog
{
public:
    about() {}
    about(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Acerca de",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(454, 233),
        long style = wxDEFAULT_DIALOG_STYLE|wxSTAY_ON_TOP, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Acerca de",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(454, 233),
        long style = wxDEFAULT_DIALOG_STYLE|wxSTAY_ON_TOP, const wxString &name = wxDialogNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void evt_key_up(wxKeyEvent& event) { event.Skip(); }

    // Class member variables

    wxGenericStaticText* m_staticText18;
    wxStaticBitmap* m_bitmap5;
    wxStaticLine* m_staticline2;
    wxStaticText* m_staticText15;
    wxStaticText* m_staticText181;
    wxStaticText* m_staticText19;
    wxStaticText* m_staticText201;
    wxStaticText* m_staticText_fechaUltimaActualizacion;
    wxStaticText* m_staticText_version;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
