///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/bitmap.h>
#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>

class searchDialog : public wxDialog
{
public:
    searchDialog() {}
    searchDialog(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Buscar...",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(286, 156),
        long style = wxDEFAULT_DIALOG_STYLE|wxSTAY_ON_TOP, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Buscar...",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(286, 156),
        long style = wxDEFAULT_DIALOG_STYLE|wxSTAY_ON_TOP, const wxString &name = wxDialogNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void evt_key_up(wxKeyEvent& event) { event.Skip(); }
    virtual void search(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxButton* m_button2;
    wxStaticText* hint;
    wxStaticText* m_staticText5;
    wxTextCtrl* search_term;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
