///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

// Imported from C:\Users\cbottazzi\Desktop\axia-traductor\wxfb_project.wxui

#include <wx/sizer.h>

#include "search_and_replace_base.h"

#include <wx/mstream.h>  // memory stream classes

// Convert a data array into a wxImage
#ifdef __cpp_inline_variables
inline wxImage wxueImage(const unsigned char* data, size_t size_data)
#else
static wxImage wxueImage(const unsigned char* data, size_t size_data)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    wxImage image;
    image.LoadFile(strm);
    return image;
};

namespace wxue_img
{
    extern const unsigned char cross_png[524];  // resources/cross.png
    extern const unsigned char edit_replace_png[438];  // resources/edit-replace.png
}

bool search_and_replace::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;
    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);

    auto* fgSizer1 = new wxFlexGridSizer(2, 0, 0);

    m_staticText6 = new wxStaticText(this, wxID_ANY, "Buscar todas las ocurrencias de");
    fgSizer1->Add(m_staticText6, wxSizerFlags().Border(wxALL));

    m_search = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_PROCESS_ENTER);
    fgSizer1->Add(m_search, wxSizerFlags().Expand().Border(wxALL));

    m_staticText7 = new wxStaticText(this, wxID_ANY, "Y reemplazarlas por");
    fgSizer1->Add(m_staticText7, wxSizerFlags().Border(wxALL));

    m_replace = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_PROCESS_ENTER);
    fgSizer1->Add(m_replace, wxSizerFlags().Expand().Border(wxALL));

    fgSizer1->AddStretchSpacer(1);

    auto* gSizer4 = new wxGridSizer(2, 0, 0);

    m_button2 = new wxButton(this, wxID_ANY, "Reemplazar");
        m_button2->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::edit_replace_png, sizeof(wxue_img::edit_replace_png))));
    gSizer4->Add(m_button2, wxSizerFlags().Border(wxALL));

    m_button3 = new wxButton(this, wxID_ANY, "Cancelar");
        m_button3->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::cross_png, sizeof(wxue_img::cross_png))));
    gSizer4->Add(m_button3, wxSizerFlags().Border(wxALL));

    fgSizer1->Add(gSizer4, wxSizerFlags(1).Expand());

    SetSizerAndFit(fgSizer1);
    Centre(wxBOTH);

    // Event handlers
    m_button3->Bind(wxEVT_BUTTON, &search_and_replace::close, this);
    m_button2->Bind(wxEVT_BUTTON, &search_and_replace::start_replace, this);
    Bind(wxEVT_KEY_UP, &search_and_replace::evt_key_up, this);
    m_replace->Bind(wxEVT_KEY_UP, &search_and_replace::evt_key_up, this);
    m_search->Bind(wxEVT_KEY_UP, &search_and_replace::evt_key_up, this);
    m_replace->Bind(wxEVT_TEXT_ENTER, &search_and_replace::start_replace, this);
    m_search->Bind(wxEVT_TEXT_ENTER, &search_and_replace::start_replace, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
