///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

// Imported from C:\Users\cbottazzi\Desktop\axia-traductor\wxfb_project.wxui

#include <wx/bmpbndl.h>
#include <wx/sizer.h>

#include "wxAboutBase.h"

#include <wx/mstream.h>  // memory stream classes

// Convert a data array into a wxImage
#ifdef __cpp_inline_variables
inline wxImage wxueImage(const unsigned char* data, size_t size_data)
#else
static wxImage wxueImage(const unsigned char* data, size_t size_data)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    wxImage image;
    image.LoadFile(strm);
    return image;
};

namespace wxue_img
{
    extern const unsigned char logo_md_png[31468];  // resources/logo_md.png
}

bool wxAboutBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;
    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);

    SetForegroundColour(wxColour("#000000"));
    SetBackgroundColour(wxColour("#F0F0F0"));

    auto* bSizer4 = new wxBoxSizer(wxVERTICAL);

    m_bitmap5 = new wxStaticBitmap(this, wxID_ANY, wxBitmapBundle::FromBitmap(wxueImage(wxue_img::logo_md_png, sizeof(wxue_img::logo_md_png))));
    m_bitmap5->SetForegroundColour(wxColour("#FFFFFF"));
    m_bitmap5->SetBackgroundColour(wxColour("#FAFAFA"));
    bSizer4->Add(m_bitmap5, wxSizerFlags(1).Expand().Border(wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_staticText18 = new wxGenericStaticText(this, wxID_ANY, wxEmptyString);
    m_staticText18->SetLabelMarkup(
    wxString::FromUTF8("Editor y convertidor de sintaxis Fagor 8025 ► 8035 / 8037 / FANUC"));
    {
        wxFontInfo font_info(10);
        font_info.FaceName("Arial");
        m_staticText18->SetFont(wxFont(font_info));
    }
    m_staticText18->SetForegroundColour(wxColour("#000000"));
    bSizer4->Add(m_staticText18, wxSizerFlags().Border(wxALL));

    m_staticline2 = new wxStaticLine(this);
    bSizer4->Add(m_staticline2, wxSizerFlags().Expand().Border(wxALL));

    auto* gSizer6 = new wxGridSizer(2, 0, 0);

    m_staticText19 = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("Puesta en producción"));
    m_staticText19->SetForegroundColour(wxColour("#000000"));
    gSizer6->Add(m_staticText19, wxSizerFlags().Border(wxALL));

    m_staticText201 = new wxStaticText(this, wxID_ANY, "22-03-2019");
    gSizer6->Add(m_staticText201, wxSizerFlags().Border(wxALL));

    m_staticText181 = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("Última actualización:"));
    gSizer6->Add(m_staticText181, wxSizerFlags().Border(wxALL));

    m_staticText_fechaUltimaActualizacion = new wxStaticText(this, wxID_ANY, "Cargando...");
    gSizer6->Add(m_staticText_fechaUltimaActualizacion, wxSizerFlags().Border(wxALL));

    bSizer4->Add(gSizer6, wxSizerFlags(1).Center());

    m_staticText_version = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("Versión 1.6"));
    {
        wxFontInfo font_info(10);
        font_info.FaceName("Arial");
        m_staticText_version->SetFont(wxFont(font_info));
    }
    bSizer4->Add(m_staticText_version, wxSizerFlags().Center().Border(wxALL));

    m_staticText15 = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("© 2019 - 2026 AXIA S.A."));
    m_staticText15->SetForegroundColour(wxColour("#A0A0A0"));
    bSizer4->Add(m_staticText15, wxSizerFlags().Right().Border(wxALL));

    SetSizer(bSizer4);
    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_KEY_UP, &wxAboutBase::evt_key_up, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
