///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/bitmap.h>
#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gauge.h>
#include <wx/gdicmn.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/statbmp.h>
#include <wx/stattext.h>

class wxActualizacionesBase : public wxDialog
{
public:
    wxActualizacionesBase() {}
    wxActualizacionesBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title =
        "Comprobar actualizaciones", const wxPoint& pos = wxDefaultPosition, const wxSize& size =
        wxSize(370, 225),
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title =
        "Comprobar actualizaciones", const wxPoint& pos = wxDefaultPosition, const wxSize& size =
        wxSize(370, 225),
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void close(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxButton* m_button6;
    wxGauge* m_gauge;
    wxStaticBitmap* m_bitmap3;
    wxStaticText* m_staticText21;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
