#ifndef __wxFormsBuilderwxfbExample__
#define __wxFormsBuilderwxfbExample__

/**
@file
Subclass of wxfbExample, which is generated by wxFormBuilder.
*/

#include "wxfb_project.h"

//// end generated include

/** Implementing wxfbExample */
class wxFormsBuilderwxfbExample : public wxfbExample
{
	protected:
		// Handlers for wxfbExample events.
		void OnButtonClose( wxCommandEvent& event );
	public:
		/** Constructor */
		wxFormsBuilderwxfbExample( wxWindow* parent );
	//// end generated class members
	
};

#endif // __wxFormsBuilderwxfbExample__
