///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/bitmap.h>
#include <wx/choice.h>
#include <wx/colour.h>
#include <wx/event.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/menu.h>
#include <wx/panel.h>
#include <wx/settings.h>
#include <wx/splitter.h>
#include <wx/statbmp.h>
#include <wx/statusbr.h>
#include <wx/toolbar.h>
#include <wx/treectrl.h>

class wxCncEditor;

class wxMainWindowBase : public wxFrame
{
public:
    wxMainWindowBase() {}
    wxMainWindowBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title =
        wxString::FromUTF8("Traductor código CNC 8025 a 8035 / 8037 / FANUC"), const wxPoint& pos =
        wxDefaultPosition, const wxSize& size = wxSize(1270, 730),
        long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL, const wxString &name = wxFrameNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title =
        wxString::FromUTF8("Traductor código CNC 8025 a 8035 / 8037 / FANUC"), const wxPoint& pos =
        wxDefaultPosition, const wxSize& size = wxSize(1270, 730),
        long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL, const wxString &name = wxFrameNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void FtpDisconnect(wxCommandEvent& event) { event.Skip(); }
    virtual void FtpRefresh(wxCommandEvent& event) { event.Skip(); }
    virtual void RenameFtpFile(wxCommandEvent& event) { event.Skip(); }
    virtual void about(wxCommandEvent& event) { event.Skip(); }
    virtual void channels(wxCommandEvent& event) { event.Skip(); }
    virtual void checkUpdates(wxCommandEvent& event) { event.Skip(); }
    virtual void connectFtpMenu(wxCommandEvent& event) { event.Skip(); }
    virtual void copy_program_clipboard(wxCommandEvent& event) { event.Skip(); }
    virtual void deleteFtpFile(wxCommandEvent& event) { event.Skip(); }
    virtual void enum_lines(wxCommandEvent& event) { event.Skip(); }
    virtual void ftpFileOptions(wxTreeEvent& event) { event.Skip(); }
    virtual void loadProgramFromFile(wxCommandEvent& event) { event.Skip(); }
    virtual void openFormSendProgram(wxCommandEvent& event) { event.Skip(); }
    virtual void openFtpFile(wxMouseEvent& event) { event.Skip(); }
    virtual void open_options(wxCommandEvent& event) { event.Skip(); }
    virtual void paste_formatting(wxCommandEvent& event) { event.Skip(); }
    virtual void paste_program_clipboard(wxCommandEvent& event) { event.Skip(); }
    virtual void save_program(wxCommandEvent& event) { event.Skip(); }
    virtual void search_next(wxCommandEvent& event) { event.Skip(); }
    virtual void search_replace_window(wxCommandEvent& event) { event.Skip(); }
    virtual void search_window(wxCommandEvent& event) { event.Skip(); }
    virtual void sendProgramOnFly(wxCommandEvent& event) { event.Skip(); }
    virtual void simulate(wxCommandEvent& event) { event.Skip(); }
    virtual void translate(wxCommandEvent& event) { event.Skip(); }
    virtual void translateFanuc(wxCommandEvent& event) { event.Skip(); }
    virtual void update_syntax_highlight(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxChoice* m_syntax_slection;
    wxCncEditor* m_editor;
    wxMenu* m_menu1;
    wxMenu* m_menu2;
    wxMenu* m_menu3;
    wxMenu* m_menu5;
    wxMenuBar* m_menubar1;
    wxPanel* m_panel1;
    wxPanel* m_panel2;
    wxSplitterWindow* m_splitter1;
    wxStaticBitmap* m_bitmap1;
    wxStatusBar* m_statusBar;
    wxToolBar* m_toolBar1;
    wxToolBar* m_toolBar2;
    wxToolBarToolBase* ftp_desconectar;
    wxToolBarToolBase* ftp_eliminar;
    wxToolBarToolBase* ftp_enviar1;
    wxToolBarToolBase* ftp_enviar;
    wxToolBarToolBase* ftp_renombrar;
    wxToolBarToolBase* m_tool10;
    wxToolBarToolBase* m_tool1;
    wxToolBarToolBase* m_tool2;
    wxToolBarToolBase* m_tool3;
    wxToolBarToolBase* m_tool4;
    wxToolBarToolBase* m_tool5;
    wxToolBarToolBase* m_tool6;
    wxTreeCtrl* m_treeCtrl1;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
