///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

// Imported from C:\Users\cbottazzi\Desktop\axia-traductor\wxfb_project.wxui

#include <wx/bmpbndl.h>
#include <wx/sizer.h>

#include "wxCncEditor.h"
#include "wxPlotPanel.h"

#include "wxMainWindowBase.h"

#include <wx/mstream.h>  // memory stream classes

// Convert a data array into a wxImage
#ifdef __cpp_inline_variables
inline wxImage wxueImage(const unsigned char* data, size_t size_data)
#else
static wxImage wxueImage(const unsigned char* data, size_t size_data)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    wxImage image;
    image.LoadFile(strm);
    return image;
};

namespace wxue_img
{
    extern const unsigned char application_browser_icon_png[841];  // resources/application-browser-icon.png
    extern const unsigned char chart_line_png[526];  // resources/chart_line.png
    extern const unsigned char copy_gif[278];  // resources/copy.gif
    extern const unsigned char cross_png[524];  // resources/cross.png
    extern const unsigned char disk_png[1063];  // resources/disk.png
    extern const unsigned char document_rename_png[765];  // resources/document-rename.png
    extern const unsigned char edit_replace_png[438];  // resources/edit-replace.png
    extern const unsigned char fagor_jpg[1666];  // resources/fagor.jpg
    extern const unsigned char fanuc_png[748];  // resources/fanuc.png
    extern const unsigned char folder_png[684];  // resources/folder.png
    extern const unsigned char information_png[741];  // resources/information.png
    extern const unsigned char logo_md_png[3467];  // resources/logo_md.png
    extern const unsigned char magnifier_png[578];  // resources/magnifier.png
    extern const unsigned char magnifier_zoom_in_png[645];  // resources/magnifier_zoom_in.png
    extern const unsigned char page_paste_png[677];  // resources/page_paste.png
    extern const unsigned char paste_plain_png[568];  // resources/paste_plain.png
    extern const unsigned char plug_connect_png[457];  // resources/plug-connect.png
    extern const unsigned char plug_disconnect_png[505];  // resources/plug-disconnect.png
    extern const unsigned char refresh_png[685];  // resources/refresh.png
    extern const unsigned char sender_ico_png[1010];  // resources/sender_ico.png
    extern const unsigned char settings_icon16_png[625];  // resources/settings-icon16.png
    extern const unsigned char text_letter_omega_png[541];  // resources/text_letter_omega.png
    extern const unsigned char text_list_numbers_png[357];  // resources/text_list_numbers.png
    extern const unsigned char wand_png[1977];  // resources/wand.png
}

bool wxMainWindowBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{

    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);
    if (!wxImage::FindHandler(wxBITMAP_TYPE_GIF))
        wxImage::AddHandler(new wxGIFHandler);
    if (!wxImage::FindHandler(wxBITMAP_TYPE_JPEG))
        wxImage::AddHandler(new wxJPEGHandler);

    if (!wxFrame::Create(parent, id, title, pos, size, style, name))
        return false;

    SetBackgroundColour(wxColour("#F0F0F0"));
    auto* bSizer1 = new wxBoxSizer(wxVERTICAL);

    auto* gSizer1 = new wxGridSizer(2, 0, 0);

    m_syntax_slection = new wxChoice(this, wxID_ANY);
    m_syntax_slection->Append("Sintaxis para 8025");
    m_syntax_slection->Append("Sintaxis para 8035");
    m_syntax_slection->SetSelection(0);
    gSizer1->Add(m_syntax_slection,
        wxSizerFlags().CenterVertical().Border(wxLEFT|wxRIGHT|wxTOP, wxSizerFlags::GetDefaultBorder()));

    m_bitmap1 = new wxStaticBitmap(this, wxID_ANY, wxBitmapBundle::FromBitmap(wxueImage(wxue_img::logo_md_png, sizeof(wxue_img::logo_md_png))),
        wxDefaultPosition, wxSize(-1, 40));
    gSizer1->Add(m_bitmap1, wxSizerFlags().Right().Border(wxALL));

    bSizer1->Add(gSizer1, wxSizerFlags().Expand());

    m_splitter1 = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize,
        wxSP_3D|wxSP_3DBORDER|wxSP_3DSASH|wxSP_BORDER);
    m_splitter1->SetSashGravity(0.0);
    bSizer1->Add(m_splitter1, wxSizerFlags(1).Expand());

    m_panel1 = new wxPanel(m_splitter1, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    auto* bSizer6 = new wxBoxSizer(wxVERTICAL);

    m_toolBar2 = new wxToolBar(m_panel1, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTB_HORIZONTAL);
    m_tool6 = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::plug_connect_png, sizeof(wxue_img::plug_connect_png)), wxNullBitmap, wxITEM_NORMAL,
        "Conectar a CNC", "Conectar a CNC");

    ftp_desconectar = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::plug_disconnect_png, sizeof(wxue_img::plug_disconnect_png)), wxNullBitmap,
        wxITEM_NORMAL, "Desconectar de control CNC", "Desconectar de control CNC");

    m_toolBar2->AddSeparator();
    m_tool10 = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::refresh_png, sizeof(wxue_img::refresh_png)), wxNullBitmap, wxITEM_NORMAL,
        "Actualizar", "Actualizar");

    ftp_eliminar = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::cross_png, sizeof(wxue_img::cross_png)), wxNullBitmap, wxITEM_NORMAL,
        "Eliminar archivo seleccionado", "Eliminar archivo seleccionado");

    ftp_renombrar = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::document_rename_png, sizeof(wxue_img::document_rename_png)), wxNullBitmap,
        wxITEM_NORMAL, "Renombrar archivo seleccionado", "Renombrar archivo seleccionado");

    ftp_enviar = m_toolBar2->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::sender_ico_png, sizeof(wxue_img::sender_ico_png)), wxNullBitmap, wxITEM_NORMAL,
        "Enviar el programa al CNC conectado", "Enviar el programa al CNC conectado");

    m_toolBar2->Realize();
    bSizer6->Add(m_toolBar2, wxSizerFlags().Expand());

    m_treeCtrl1 = new wxTreeCtrl(m_panel1, wxID_ANY);
    bSizer6->Add(m_treeCtrl1, wxSizerFlags(1).Expand().Border(wxALL));
    m_panel1->SetSizerAndFit(bSizer6);

    m_panel2 = new wxPanel(m_splitter1, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    auto* bSizer7 = new wxBoxSizer(wxVERTICAL);

    m_plotSplitter = new wxSplitterWindow(m_panel2, wxID_ANY, wxDefaultPosition, wxDefaultSize,
        wxSP_3D|wxSP_LIVE_UPDATE);
    m_plotSplitter->SetSashGravity(0.0);
    m_plotSplitter->SetMinimumPaneSize(80);
    bSizer7->Add(m_plotSplitter, wxSizerFlags(1).Expand().Border(wxALL));

    m_editorPanel = new wxPanel(m_plotSplitter, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    auto* bSizer8 = new wxBoxSizer(wxVERTICAL);

    m_editor = new wxCncEditor( m_editorPanel, wxID_ANY );
    bSizer8->Add(m_editor, wxSizerFlags(1).Expand());
    m_editorPanel->SetSizerAndFit(bSizer8);

    m_plotPanel = new wxPanel(m_plotSplitter, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    auto* bSizer9 = new wxBoxSizer(wxVERTICAL);

    m_plot = new wxPlotPanel( m_plotPanel, wxID_ANY );
    bSizer9->Add(m_plot, wxSizerFlags(1).Expand());
    m_plotPanel->SetSizerAndFit(bSizer9);
    m_plotSplitter->SplitVertically(m_editorPanel, m_plotPanel);
    m_plotSplitter->SetSashPosition(700);
    m_panel2->SetSizerAndFit(bSizer7);
    m_splitter1->SplitVertically(m_panel1, m_panel2);
    m_splitter1->SetSashPosition(242);
    SetSizer(bSizer1);

    m_statusBar = CreateStatusBar(3);

    m_toolBar1 = CreateToolBar();
    m_toolBar1->SetBackgroundColour(wxColour("#D5D5FF"));
    m_tool1 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::folder_png, sizeof(wxue_img::folder_png)), wxNullBitmap, wxITEM_NORMAL,
        "Cargar archivo", "Cargar un archivo generado para 8025");

    m_tool2 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::disk_png, sizeof(wxue_img::disk_png)), wxNullBitmap, wxITEM_NORMAL, "Guardar archivo",
        "Guardar archivo en el estado actual");

    m_toolBar1->AddSeparator();
    m_tool3 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::wand_png, sizeof(wxue_img::wand_png)), wxNullBitmap, wxITEM_NORMAL,
        wxString::FromUTF8("Actualizar coloración de sintaxis"),
        wxString::FromUTF8("Actualizar coloración de sintaxis"));

    m_tool4 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::fagor_jpg, sizeof(wxue_img::fagor_jpg)), wxNullBitmap, wxITEM_NORMAL,
        wxString::FromUTF8("Convertir código a Fagor 8035 / 8037 (F9)"),
        wxString::FromUTF8("Convertir código a Fagor 8035 / 8037  (F9)"));

    m_tool5 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::fanuc_png, sizeof(wxue_img::fanuc_png)), wxNullBitmap, wxITEM_NORMAL,
        wxString::FromUTF8("Convertir código a Fanuc (F10)"),
        wxString::FromUTF8("Convertir código a Fanuc (F10)"));

    m_toolBar1->AddSeparator();
    ftp_enviar1 = m_toolBar1->AddTool(wxID_ANY, "tool",
        wxueImage(wxue_img::sender_ico_png, sizeof(wxue_img::sender_ico_png)), wxNullBitmap, wxITEM_NORMAL,
        "Enviar el programa al CNC conectado", "Enviar el programa al CNC conectado");

    m_toolBar1->Realize();

    m_menubar1 = new wxMenuBar();

    m_menu1 = new wxMenu();
    auto* m_menuItem1 = new wxMenuItem(m_menu1, wxID_ANY, "Cargar archivo\tCTRL+O");
    m_menuItem1->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::folder_png, sizeof(wxue_img::folder_png))));

    m_menu1->Append(m_menuItem1);
    auto* m_menuItem2 = new wxMenuItem(m_menu1, wxID_ANY, "Guardar programa\tCTRL+S");
    m_menuItem2->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::disk_png, sizeof(wxue_img::disk_png))));

    m_menu1->Append(m_menuItem2);
    m_menubar1->Append(m_menu1, "&Archivo");

    m_menu3 = new wxMenu();
    auto* m_menuItem13 = new wxMenuItem(m_menu3, wxID_ANY,
        wxString::FromUTF8("Pegar formateando a código NC\tCTRL+ALT+V"));
    m_menuItem13->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::page_paste_png, sizeof(wxue_img::page_paste_png))));

    m_menu3->Append(m_menuItem13);
    auto* m_menuItem10 = new wxMenuItem(m_menu3, wxID_ANY, "Copiar programa completo\tCTRL+SHIFT+C");
    m_menuItem10->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::copy_gif, sizeof(wxue_img::copy_gif))));

    m_menu3->Append(m_menuItem10);
    auto* m_menuItem11 = new wxMenuItem(m_menu3, wxID_ANY, "Pegar reemplazando todo\tCTRL+SHIFT+V");
    m_menuItem11->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::paste_plain_png, sizeof(wxue_img::paste_plain_png))));

    m_menu3->Append(m_menuItem11);
    m_menu3->AppendSeparator();
    auto* m_menuItem5 = new wxMenuItem(m_menu3, wxID_ANY, "Buscar\tCTRL+F");
    m_menuItem5->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::magnifier_png, sizeof(wxue_img::magnifier_png))));

    m_menu3->Append(m_menuItem5);
    auto* m_search_next = new wxMenuItem(m_menu3, wxID_ANY, "Buscar siguiente\tF3",
        wxString::FromUTF8("Buscar próximo término"), wxITEM_NORMAL);
    m_search_next->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::magnifier_zoom_in_png, sizeof(wxue_img::magnifier_zoom_in_png))));

    m_menu3->Append(m_search_next);
    auto* m_menuItem7 = new wxMenuItem(m_menu3, wxID_ANY, "Buscar y reemplazar\tCTRL+R");
    m_menuItem7->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::edit_replace_png, sizeof(wxue_img::edit_replace_png))));

    m_menu3->Append(m_menuItem7);
    m_menu3->AppendSeparator();
    auto* m_menuItem9 = new wxMenuItem(m_menu3, wxID_ANY,
        wxString::FromUTF8("Enumerar / Re-enumerar líneas\tF8"));
    m_menuItem9->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::text_list_numbers_png, sizeof(wxue_img::text_list_numbers_png))));

    m_menu3->Append(m_menuItem9);
    m_menu3->AppendSeparator();
    auto* m_menuItem18 = new wxMenuItem(m_menu3, wxID_ANY, wxString::FromUTF8("Parámetros\tF7"));
    m_menuItem18->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::settings_icon16_png, sizeof(wxue_img::settings_icon16_png))));

    m_menu3->Append(m_menuItem18);
    m_menubar1->Append(m_menu3, "Editar");

    m_menu2 = new wxMenu();
    auto* m_menuItem3 = new wxMenuItem(m_menu2, wxID_ANY,
        wxString::FromUTF8("Actualizar coloración de sintaxis\tF11"));
    m_menuItem3->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::refresh_png, sizeof(wxue_img::refresh_png))));

    m_menu2->Append(m_menuItem3);
    auto* m_menuItem4 = new wxMenuItem(m_menu2, wxID_ANY, "Convertir a 8035\tF9");
    m_menuItem4->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::fagor_jpg, sizeof(wxue_img::fagor_jpg))));

    m_menu2->Append(m_menuItem4);
    auto* m_menuItem41 = new wxMenuItem(m_menu2, wxID_ANY, "Convertir a FANUC\tF10");
    m_menuItem41->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::fanuc_png, sizeof(wxue_img::fanuc_png))));

    m_menu2->Append(m_menuItem41);
    m_menu2->AppendSeparator();
    auto* m_menuItem14 = new wxMenuItem(m_menu2, wxID_ANY, "Simular\tF4");
    m_menuItem14->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::chart_line_png, sizeof(wxue_img::chart_line_png))));

    m_menu2->Append(m_menuItem14);
    auto* m_menuItem12 = new wxMenuItem(m_menu2, wxID_ANY, "Canales\tF5");
    m_menuItem12->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::text_letter_omega_png, sizeof(wxue_img::text_letter_omega_png))));

    m_menu2->Append(m_menuItem12);
    m_menu2->AppendSeparator();
    auto* m_menuItem15 = new wxMenuItem(m_menu2, wxID_ANY, "Enviar programa a torno\tF2");
    m_menuItem15->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::sender_ico_png, sizeof(wxue_img::sender_ico_png))));

    m_menu2->Append(m_menuItem15);
    m_menubar1->Append(m_menu2, "&Herramientas");

    m_menu5 = new wxMenu();
    auto* m_menuItem8 = new wxMenuItem(m_menu5, wxID_ANY, "Acerca de...\tF12",
        wxString::FromUTF8("Información del programa"), wxITEM_NORMAL);
    m_menuItem8->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::information_png, sizeof(wxue_img::information_png))));

    m_menu5->Append(m_menuItem8);
    auto* m_menuItem19 = new wxMenuItem(m_menu5, wxID_ANY, "Comprobar actualizaciones",
        "Comprobar si hay actualizaciones del software", wxITEM_NORMAL);
    m_menuItem19->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::application_browser_icon_png, sizeof(wxue_img::application_browser_icon_png))));

    m_menu5->Append(m_menuItem19);
    m_menubar1->Append(m_menu5, "Ayuda");

    SetMenuBar(m_menubar1);

    Centre(wxBOTH);

    // Event handlers
    m_syntax_slection->Bind(wxEVT_CHOICE, &wxMainWindowBase::update_syntax_highlight, this);
    m_treeCtrl1->Bind(wxEVT_LEFT_DCLICK, &wxMainWindowBase::openFtpFile, this);
    Bind(wxEVT_MENU, &wxMainWindowBase::about, this, m_menuItem8->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::channels, this, m_menuItem12->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::checkUpdates, this, m_menuItem19->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::copy_program_clipboard, this, m_menuItem10->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::enum_lines, this, m_menuItem9->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::loadProgramFromFile, this, m_menuItem1->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::openFormSendProgram, this, m_menuItem15->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::open_options, this, m_menuItem18->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::paste_formatting, this, m_menuItem13->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::paste_program_clipboard, this, m_menuItem11->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::save_program, this, m_menuItem2->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::search_next, this, m_search_next->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::search_replace_window, this, m_menuItem7->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::search_window, this, m_menuItem5->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::simulate, this, m_menuItem14->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::translate, this, m_menuItem4->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::translateFanuc, this, m_menuItem41->GetId());
    Bind(wxEVT_MENU, &wxMainWindowBase::update_syntax_highlight, this, m_menuItem3->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::FtpDisconnect, this, ftp_desconectar->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::FtpRefresh, this, m_tool10->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::RenameFtpFile, this, ftp_renombrar->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::connectFtpMenu, this, m_tool6->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::deleteFtpFile, this, ftp_eliminar->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::loadProgramFromFile, this, m_tool1->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::save_program, this, m_tool2->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::sendProgramOnFly, this, ftp_enviar->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::sendProgramOnFly, this, ftp_enviar1->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::translate, this, m_tool4->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::translateFanuc, this, m_tool5->GetId());
    Bind(wxEVT_TOOL, &wxMainWindowBase::update_syntax_highlight, this, m_tool3->GetId());
    m_treeCtrl1->Bind(wxEVT_TREE_ITEM_MENU, &wxMainWindowBase::ftpFileOptions, this);

    return true;
}

namespace wxue_img
{
    // resources/application-browser-icon.png
    const unsigned char application_browser_icon_png[841] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,3,0,0,0,40,45,15,83,0,0,0,25,116,
        69,88,116,83,111,102,116,119,97,114,101,0,65,100,111,98,101,32,73,109,97,103,101,82,101,97,100,121,
        113,201,101,60,0,0,1,224,80,76,84,69,71,112,76,81,81,81,77,77,77,85,85,85,0,0,0,0,0,0,16,16,16,0,
        0,0,0,65,130,85,85,85,82,82,82,85,85,85,85,85,85,73,73,73,0,49,98,50,50,50,68,68,68,56,56,56,39,
        39,39,62,62,62,13,13,13,80,80,80,0,74,141,1,86,158,2,116,198,2,101,178,3,129,216,198,198,198,21,
        122,190,3,3,3,184,184,196,255,255,255,252,252,252,248,248,248,244,244,244,235,235,235,187,222,246,
        118,191,240,85,176,238,88,164,218,137,195,231,161,217,244,126,184,223,215,229,239,104,178,223,79,
        163,216,69,160,216,95,169,218,94,157,206,56,152,212,130,190,228,40,140,205,87,170,220,59,155,212,
        41,140,206,186,231,248,128,187,228,250,250,250,47,143,205,42,141,206,37,133,201,41,138,203,93,173,
        222,62,156,213,125,189,228,219,234,245,232,235,238,72,158,215,77,142,194,253,253,253,165,212,239,
        204,242,254,65,149,212,67,158,229,50,138,206,60,149,207,56,128,188,173,217,242,105,176,223,94,173,
        230,239,239,239,171,196,217,247,247,247,62,144,215,105,163,209,171,215,239,101,178,230,167,216,243,
        116,182,232,50,101,151,119,197,253,92,160,210,84,173,245,100,146,185,155,206,239,198,234,248,243,
        243,243,195,233,248,204,242,252,165,213,241,237,237,237,191,237,255,64,115,162,230,230,230,29,116,
        185,108,187,245,240,240,240,226,226,226,78,147,201,234,234,234,231,231,231,215,250,255,143,209,250,
        62,143,206,126,181,220,187,187,187,96,176,230,245,249,252,163,217,244,174,232,255,202,240,252,215,
        249,255,122,191,237,202,245,255,198,244,255,158,211,240,186,186,186,207,242,252,107,185,235,178,
        217,242,177,225,247,102,179,231,246,250,253,147,201,237,168,214,242,184,184,184,220,220,220,156,
        156,156,182,182,182,217,217,216,70,169,236,158,158,158,213,213,213,179,179,179,160,160,160,203,203,
        215,199,199,209,163,163,163,176,176,176,209,209,208,166,166,166,198,198,205,204,204,204,174,174,
        174,168,168,168,197,197,201,198,198,198,197,197,198,171,171,171,200,200,200,5,118,110,59,0,0,0,31,
        116,82,78,83,0,104,106,103,22,9,133,26,204,102,91,34,89,108,157,118,110,115,123,113,103,105,203,
        200,194,197,192,212,169,102,212,1,67,38,119,0,0,0,212,73,68,65,84,24,211,99,96,64,7,220,60,156,72,
        128,135,155,129,75,186,163,187,111,234,140,249,115,230,206,158,62,105,162,28,23,131,104,113,93,123,
        87,255,148,153,243,102,77,155,60,161,183,83,150,129,89,30,5,48,51,48,186,42,0,65,169,138,170,90,
        143,154,170,74,11,35,3,147,165,162,162,162,99,88,73,107,91,99,125,83,67,51,19,3,111,144,146,146,
        182,186,69,104,82,114,92,124,126,101,173,12,131,64,66,128,147,129,150,134,185,187,155,111,98,69,
        117,141,20,131,112,150,114,160,139,190,142,166,145,67,120,106,81,89,185,4,131,96,74,122,108,136,
        179,158,174,137,157,95,116,78,65,149,36,3,127,110,118,90,132,135,149,161,169,189,183,127,84,102,
        161,56,131,144,114,94,164,143,167,141,177,153,181,173,87,112,76,134,24,131,8,27,27,7,18,224,99,96,
        101,97,71,2,44,172,24,190,7,0,83,41,53,216,60,217,77,27,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/chart_line.png
    const unsigned char chart_line_png[526] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        103,65,77,65,0,0,175,200,55,5,138,233,0,0,0,25,116,69,88,116,83,111,102,116,119,97,114,101,0,65,
        100,111,98,101,32,73,109,97,103,101,82,101,97,100,121,113,201,101,60,0,0,1,160,73,68,65,84,56,203,
        99,248,255,255,63,3,37,152,44,77,95,189,124,11,190,184,122,60,248,108,239,92,64,150,1,95,156,221,
        31,255,153,57,253,255,39,75,187,135,164,107,118,114,99,251,108,235,116,247,147,133,237,251,143,198,
        150,164,187,224,147,141,99,239,71,115,155,93,31,140,44,152,9,134,129,107,253,197,2,151,218,115,15,
        157,170,78,23,128,53,91,59,4,126,52,179,121,242,193,208,92,20,30,136,191,179,51,215,255,78,79,253,
        253,43,57,105,61,186,1,206,53,103,159,204,217,120,225,127,193,252,189,255,163,178,215,158,125,97,
        225,248,173,55,168,182,217,60,123,91,155,105,198,166,7,198,105,235,10,24,126,167,165,254,254,183,
        117,211,255,159,177,177,127,127,68,68,154,33,52,159,177,119,172,60,249,193,190,236,232,27,183,130,
        221,213,207,205,29,111,175,115,77,221,102,150,189,117,181,73,198,198,223,61,11,15,252,55,72,90,245,
        128,225,103,98,194,250,159,49,49,191,127,132,71,92,250,30,20,114,239,155,175,255,201,21,113,77,139,
        156,202,143,61,180,43,59,98,15,50,12,24,88,51,63,232,153,110,132,25,110,148,178,166,192,32,105,229,
        35,189,248,165,168,129,8,244,47,91,127,202,228,221,103,124,147,62,125,176,117,126,5,12,172,107,192,
        192,250,243,94,215,228,235,123,13,3,126,188,9,9,232,95,9,199,170,83,199,236,203,143,45,181,45,57,
        196,9,12,44,3,96,96,253,253,55,109,202,255,119,234,250,127,112,166,68,215,186,11,5,64,255,62,7,250,
        247,13,208,191,165,200,146,239,181,141,214,191,83,211,251,253,86,73,123,61,78,3,156,170,207,60,152,
        188,230,226,127,160,127,95,146,149,23,28,42,142,23,216,149,30,126,96,83,180,191,128,110,153,137,
        170,6,0,0,198,244,184,65,236,172,238,240,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/copy.gif
    const unsigned char copy_gif[278] {
        71,73,70,56,57,97,16,0,16,0,196,31,0,114,144,174,236,241,246,199,227,254,229,237,246,242,246,250,
        213,219,228,193,212,225,170,211,251,188,221,253,137,176,202,85,107,139,149,202,252,131,187,232,72,
        84,105,175,210,229,179,217,252,118,183,233,84,98,123,159,196,216,91,122,158,223,232,239,41,49,67,
        65,72,87,61,68,85,168,203,223,125,161,188,215,231,240,124,163,192,142,193,239,161,208,251,255,255,
        255,255,255,255,33,249,4,1,0,0,31,0,44,0,0,0,0,16,0,16,0,0,5,147,160,39,142,227,103,158,159,103,
        56,142,148,100,0,224,161,166,231,104,195,16,228,220,84,214,142,129,64,176,106,189,98,179,20,134,
        32,96,225,116,60,95,74,194,228,4,135,2,4,129,195,80,136,18,76,198,18,171,37,16,188,30,176,128,65,
        29,34,16,143,7,33,34,218,4,16,12,245,251,113,56,16,26,34,0,119,16,122,124,7,29,3,128,30,0,4,8,16,
        118,123,135,136,138,19,5,4,6,130,112,135,11,11,20,22,129,10,10,17,140,154,29,156,1,23,36,34,149,
        4,57,20,20,1,6,21,73,53,0,161,17,13,13,22,23,21,116,40,170,192,30,33,0,59
    };
    // resources/cross.png
    const unsigned char cross_png[524] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,195,73,68,65,84,56,203,165,147,63,107,27,65,16,197,127,
        235,147,13,50,33,199,246,137,113,99,163,144,114,67,84,229,15,164,57,55,81,33,130,8,152,20,110,156,
        34,133,81,97,55,87,238,87,8,164,86,147,175,32,98,112,147,50,58,174,8,10,1,171,50,50,106,68,206,56,
        74,17,223,94,38,133,246,108,201,74,42,45,44,236,238,155,121,188,153,55,171,68,132,101,214,10,75,
        174,10,192,71,165,80,64,0,17,96,129,184,128,174,155,9,186,141,9,240,90,100,78,65,84,128,125,117,
        116,100,138,105,96,116,27,123,121,112,176,128,173,0,20,128,3,219,58,60,52,253,126,159,102,187,109,
        220,77,96,228,192,190,216,219,51,131,193,128,39,187,187,198,129,45,60,129,18,17,58,74,1,68,2,182,
        177,191,111,210,52,165,86,171,241,169,211,73,0,234,141,134,25,141,70,132,97,200,215,227,227,68,65,
        12,116,223,136,220,16,200,84,69,36,96,159,55,155,102,112,122,74,24,134,76,38,19,206,135,67,170,213,
        42,63,207,206,18,5,113,5,186,10,88,32,200,167,229,68,2,246,254,214,150,249,49,30,3,16,4,1,151,227,
        113,162,32,14,160,187,10,148,4,21,128,115,255,176,230,59,174,128,252,226,130,245,178,83,69,65,14,
        165,74,174,252,121,97,14,196,55,108,91,107,83,117,142,59,112,189,183,181,54,14,172,204,187,51,111,
        99,14,182,174,181,41,147,210,44,75,210,44,75,202,123,93,107,147,255,203,70,55,173,223,238,204,36,
        159,100,89,226,32,118,16,159,204,144,236,120,18,119,45,91,132,13,160,5,81,27,122,223,181,150,54,
        244,90,16,109,2,155,255,193,54,124,174,18,17,148,82,247,128,245,71,240,244,33,188,253,6,239,191,
        192,103,224,55,240,7,88,123,12,207,30,192,187,62,124,232,77,177,95,34,50,44,9,238,2,171,222,136,
        153,225,164,240,13,15,188,65,21,143,231,192,149,136,92,170,101,191,243,95,35,220,208,19,6,20,6,173,
        0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/disk.png
    const unsigned char disk_png[1063] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,24,0,0,0,24,8,6,0,0,0,224,119,61,248,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,3,222,73,68,65,84,72,199,181,149,207,138,28,85,20,198,127,
        231,86,117,79,166,39,157,153,104,98,178,9,38,8,162,239,144,136,72,204,194,165,139,60,135,24,119,
        6,196,39,112,235,19,136,16,131,43,49,42,4,69,193,39,48,144,33,34,153,133,76,162,38,227,244,223,234,
        186,231,124,46,170,186,166,59,127,208,141,5,85,183,238,229,114,190,251,125,231,156,239,194,255,252,
        24,192,7,215,174,189,158,82,113,181,174,23,156,216,222,225,205,183,223,97,123,120,130,162,72,96,
        134,181,111,74,9,51,64,32,5,82,128,132,34,56,28,143,249,238,214,87,252,253,248,49,69,89,112,242,
        228,201,27,31,94,191,126,167,4,152,76,38,87,247,247,31,124,212,239,247,173,40,122,188,242,234,107,
        218,58,182,97,237,33,100,237,65,26,32,212,224,153,82,51,146,12,141,103,149,125,121,227,115,166,211,
        169,0,75,150,0,62,46,1,234,69,205,70,191,79,74,73,138,160,72,198,31,7,99,173,48,149,117,124,193,
        64,214,44,200,172,1,222,57,190,161,136,32,34,0,84,215,53,0,37,64,68,48,24,12,0,44,20,148,69,210,
        133,179,59,29,3,192,232,104,52,140,204,172,99,38,164,131,241,220,34,2,119,151,153,153,187,175,3,
        44,159,136,32,25,148,133,61,149,48,177,12,215,236,147,32,36,66,162,246,230,244,203,88,30,43,0,238,
        142,53,156,21,17,100,15,126,253,253,241,138,68,146,86,80,212,164,182,193,106,6,134,131,254,154,68,
        225,241,52,3,51,179,240,96,145,93,47,110,111,174,75,164,142,129,36,76,106,198,144,144,164,217,34,
        155,251,127,144,200,195,169,179,51,175,242,115,229,81,131,211,72,212,174,53,18,249,145,68,107,0,
        238,208,74,228,238,212,57,248,107,52,146,117,129,17,43,26,169,251,44,117,130,225,160,47,247,14,64,
        207,102,208,74,84,187,107,176,81,118,61,213,21,232,81,68,83,147,24,83,3,160,58,135,185,7,225,46,
        204,108,25,179,73,114,196,178,196,53,30,143,248,249,199,31,40,138,66,101,81,80,20,5,41,37,89,50,
        172,105,30,34,66,146,240,8,121,118,178,103,194,93,147,241,232,95,24,128,121,85,241,245,205,207,196,
        82,180,85,6,235,243,110,93,235,123,4,216,211,57,96,53,164,158,253,191,58,127,222,158,246,63,158,
        87,69,71,54,104,164,214,224,90,153,176,53,179,107,154,192,35,136,54,185,107,213,232,79,52,218,106,
        53,154,25,239,93,123,95,167,78,157,90,182,152,158,213,212,146,116,243,139,155,124,127,251,54,30,
        161,126,191,207,240,248,113,0,229,156,143,0,114,93,47,41,26,64,175,215,83,68,216,238,221,93,246,
        246,238,43,34,236,220,185,115,156,191,112,161,49,62,51,147,36,119,183,126,175,199,96,48,144,71,88,
        206,153,156,179,218,158,61,2,168,115,126,66,29,195,128,59,119,126,225,219,91,223,144,115,230,173,
        203,151,121,249,252,121,36,209,6,34,231,76,181,168,136,246,78,8,119,150,46,186,204,218,147,12,150,
        110,128,71,52,190,148,51,238,46,15,103,54,155,45,3,203,221,201,57,107,62,159,147,235,154,136,232,
        26,173,44,203,117,187,206,71,12,12,32,165,164,136,176,92,119,193,108,81,85,76,167,211,110,94,215,
        181,234,186,182,217,116,198,98,177,80,68,216,50,120,68,216,26,131,170,170,70,169,40,58,137,138,162,
        96,58,153,48,153,78,121,116,240,24,73,204,231,21,227,241,152,186,174,151,172,168,235,154,233,108,
        74,85,205,137,16,6,84,109,245,173,117,242,221,123,247,62,61,115,250,244,149,19,195,225,21,0,47,75,
        102,243,185,46,189,113,137,139,151,46,226,238,170,170,138,209,104,212,73,150,115,38,34,84,85,21,
        213,188,2,80,74,169,171,178,63,31,61,26,36,179,84,2,76,103,211,252,219,222,253,79,206,190,116,230,
        133,126,175,55,180,148,210,238,238,238,177,205,205,205,18,40,205,172,112,247,34,220,201,238,2,92,
        82,14,247,60,153,76,22,163,201,184,146,212,222,211,9,51,234,209,120,180,23,82,81,182,136,11,224,
        167,253,135,15,222,5,138,225,206,118,207,204,182,182,182,182,138,141,141,141,162,215,235,37,73,182,
        244,160,214,107,252,240,240,176,222,28,12,102,251,15,31,86,57,231,180,82,136,14,28,0,249,31,227,
        136,51,160,28,200,0,220,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/document-rename.png
    const unsigned char document_rename_png[765] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,25,
        116,69,88,116,83,111,102,116,119,97,114,101,0,65,100,111,98,101,32,73,109,97,103,101,82,101,97,100,
        121,113,201,101,60,0,0,2,159,73,68,65,84,120,218,140,83,95,72,83,97,20,255,237,238,206,237,58,7,
        78,184,138,179,82,11,123,16,95,74,18,95,164,48,72,36,203,151,124,152,152,207,66,175,86,80,15,138,
        79,62,228,75,73,152,244,52,4,65,66,163,30,68,165,94,70,185,194,134,96,41,145,32,51,103,98,83,155,
        110,187,107,187,187,95,231,220,253,193,136,162,3,63,190,203,57,231,251,157,251,59,231,124,22,181,
        166,6,23,123,123,145,55,139,197,114,141,142,74,252,219,94,27,134,177,110,100,50,144,171,234,234,
        32,132,40,68,232,219,227,27,24,24,75,81,48,205,48,12,100,40,158,207,89,94,94,134,111,97,161,143,
        107,17,190,72,235,139,139,240,79,76,128,217,114,176,24,124,41,157,54,145,74,38,161,197,227,136,197,
        98,56,58,58,50,207,103,67,67,99,148,119,153,8,234,172,69,69,69,136,70,34,216,219,220,68,85,125,61,
        87,186,112,163,181,245,106,112,105,9,11,179,179,144,36,9,175,230,230,204,234,106,69,5,86,87,87,241,
        126,101,5,181,170,218,241,114,126,126,23,37,37,37,102,18,67,173,174,70,71,127,255,173,68,58,45,126,
        36,18,98,63,30,23,195,35,35,226,91,52,42,54,34,17,241,121,103,71,124,218,222,22,31,195,97,17,58,
        60,20,156,43,219,108,54,111,113,113,241,41,174,160,237,237,97,105,106,234,196,227,202,74,83,179,
        169,154,228,248,198,199,81,238,241,224,82,91,27,160,235,208,201,199,166,147,92,185,161,161,161,194,
        231,243,13,255,173,221,147,147,147,240,122,189,120,27,8,192,97,179,101,157,68,66,211,66,70,215,45,
        178,170,170,25,135,195,129,123,79,37,132,66,27,216,218,10,83,208,137,178,178,211,152,126,224,130,
        166,105,224,184,211,233,132,205,106,45,16,91,179,4,146,92,90,90,106,144,4,114,37,255,168,206,254,
        36,77,129,79,69,81,32,209,165,60,137,149,78,157,9,92,46,151,193,193,39,119,21,114,187,9,231,127,
        35,97,2,142,219,237,118,147,128,141,73,172,212,116,157,37,16,123,120,112,112,176,47,127,225,48,149,
        58,115,179,171,235,182,200,110,149,41,225,67,48,8,183,219,93,32,40,72,72,167,37,153,154,241,130,
        71,200,182,79,201,239,194,225,59,15,155,154,192,203,196,36,143,70,71,113,174,177,17,6,145,25,185,
        238,35,183,134,44,65,202,59,130,107,107,120,19,10,153,191,197,193,153,233,105,244,116,119,227,122,
        103,39,122,123,122,240,124,102,38,187,47,20,205,131,115,209,210,210,82,96,61,217,220,140,179,237,
        237,247,69,206,168,162,160,89,11,122,19,226,167,174,139,36,45,88,34,149,18,177,100,82,240,178,113,
        174,228,247,251,243,247,149,175,129,64,121,244,224,192,126,236,101,22,170,114,211,24,50,53,80,150,
        101,115,10,156,107,57,214,240,50,130,71,169,173,189,34,41,138,138,255,48,67,211,190,255,18,96,0,
        126,226,79,34,8,137,67,18,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/edit-replace.png
    const unsigned char edit_replace_png[438] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,109,73,68,65,84,56,203,165,211,63,107,84,81,16,5,240,223,
        188,77,86,83,200,170,133,44,65,130,136,104,179,150,97,19,176,72,19,196,63,88,217,72,10,137,69,64,
        176,23,43,53,169,4,53,40,130,177,54,34,193,206,66,20,4,241,19,8,98,161,34,162,88,169,159,64,137,
        25,139,220,199,238,90,24,101,7,14,239,206,229,158,115,103,206,155,27,153,105,152,168,12,25,35,80,
        85,213,5,204,224,59,46,227,219,86,196,215,95,54,6,42,184,131,6,94,254,11,25,50,83,102,14,180,48,
        250,63,45,221,93,94,148,73,100,166,170,170,224,25,62,224,64,57,179,138,251,127,19,121,245,233,215,
        192,141,77,252,196,81,60,196,185,173,170,88,89,190,186,105,98,159,192,155,178,110,148,188,142,14,
        174,244,229,143,176,118,239,214,226,64,5,219,208,40,115,209,45,121,29,103,240,14,167,241,182,228,
        61,55,113,19,159,255,192,41,136,136,126,204,70,196,181,136,120,82,239,213,2,198,247,31,49,191,244,
        245,248,193,238,121,99,187,59,38,166,174,155,158,123,95,19,219,17,241,160,224,70,68,60,175,5,170,
        154,124,114,225,49,44,236,61,124,118,114,162,187,100,108,87,39,49,179,179,61,13,183,139,63,115,229,
        219,28,24,229,66,134,139,88,201,220,88,47,109,188,104,181,167,96,31,154,125,254,108,199,120,102,
        246,90,40,17,229,15,140,30,58,246,52,119,236,153,60,129,22,46,225,99,193,124,153,153,53,180,34,51,
        55,205,232,9,84,5,141,130,145,190,117,163,156,9,172,227,71,12,251,156,127,3,216,223,105,222,220,
        213,188,214,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/fagor.jpg
    const unsigned char fagor_jpg[1666] {
        255,216,255,224,0,16,74,70,73,70,0,1,1,1,0,96,0,96,0,0,255,225,0,34,69,120,105,102,0,0,77,77,0,42,
        0,0,0,8,0,1,1,18,0,3,0,0,0,1,0,1,0,0,0,0,0,0,255,219,0,67,0,2,1,1,2,1,1,2,2,2,2,2,2,2,2,3,5,3,3,
        3,3,3,6,4,4,3,5,7,6,7,7,7,6,7,7,8,9,11,9,8,8,10,8,7,7,10,13,10,10,11,12,12,12,12,7,9,14,15,13,12,
        14,11,12,12,12,255,219,0,67,1,2,2,2,3,3,3,6,3,3,6,12,8,7,8,12,12,12,12,12,12,12,12,12,12,12,12,12,
        12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,
        12,12,12,12,12,255,192,0,17,8,0,32,0,32,3,1,34,0,2,17,1,3,17,1,255,196,0,31,0,0,1,5,1,1,1,1,1,1,
        0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,255,196,0,181,16,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,125,1,2,3,
        0,4,17,5,18,33,49,65,6,19,81,97,7,34,113,20,50,129,145,161,8,35,66,177,193,21,82,209,240,36,51,98,
        114,130,9,10,22,23,24,25,26,37,38,39,40,41,42,52,53,54,55,56,57,58,67,68,69,70,71,72,73,74,83,84,
        85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,121,122,131,132,133,134,
        135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,166,167,168,169,170,178,179,
        180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,211,212,213,214,215,216,217,
        218,225,226,227,228,229,230,231,232,233,234,241,242,243,244,245,246,247,248,249,250,255,196,0,31,
        1,0,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,255,196,0,181,17,0,2,1,2,4,4,3,4,7,5,
        4,4,0,1,2,119,0,1,2,3,17,4,5,33,49,6,18,65,81,7,97,113,19,34,50,129,8,20,66,145,161,177,193,9,35,
        51,82,240,21,98,114,209,10,22,36,52,225,37,241,23,24,25,26,38,39,40,41,42,53,54,55,56,57,58,67,68,
        69,70,71,72,73,74,83,84,85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,
        121,122,130,131,132,133,134,135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,
        166,167,168,169,170,178,179,180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,
        211,212,213,214,215,216,217,218,226,227,228,229,230,231,232,233,234,242,243,244,245,246,247,248,
        249,250,255,218,0,12,3,1,0,2,17,3,17,0,63,0,253,246,158,82,177,179,42,52,140,160,144,171,141,205,
        236,51,129,237,201,2,191,55,255,0,106,59,79,248,40,135,198,255,0,22,220,127,194,21,165,248,95,225,
        111,133,85,136,182,177,211,245,187,11,139,249,19,63,43,92,92,200,172,119,250,136,66,40,206,62,108,
        110,63,81,255,0,193,74,238,124,3,166,254,201,90,197,247,196,237,83,199,26,55,130,236,47,44,230,191,
        187,240,172,179,69,125,25,51,42,71,150,136,23,17,121,142,155,177,199,76,241,95,149,159,26,255,0,
        105,15,217,7,194,31,14,181,11,175,2,248,131,246,141,241,151,138,138,21,176,177,188,241,86,163,167,
        218,9,72,225,231,149,153,72,140,117,34,48,204,122,12,103,112,249,172,251,25,78,11,217,85,169,200,
        173,125,39,203,39,248,55,247,110,126,221,225,31,12,227,113,83,250,246,11,7,245,137,57,114,46,124,
        51,175,74,47,71,171,117,33,4,245,215,153,59,45,83,71,109,227,79,218,223,246,214,255,0,130,91,73,
        163,235,95,23,188,85,225,15,21,104,186,164,254,76,62,27,214,53,59,91,171,237,81,70,60,198,129,224,
        140,92,71,176,99,50,49,104,208,178,229,88,178,169,253,76,253,143,63,106,223,11,254,218,127,0,180,
        63,136,30,19,105,151,79,213,21,163,184,181,184,3,237,26,109,210,28,77,109,40,28,110,70,238,56,101,
        42,195,42,192,215,242,247,226,95,19,234,62,49,214,36,191,213,111,111,53,11,201,20,33,150,234,226,
        75,135,85,4,144,129,228,102,125,171,147,128,88,253,79,90,253,154,255,0,131,95,180,157,94,215,246,
        106,248,151,119,112,28,104,119,126,41,141,108,67,41,1,167,75,72,196,236,15,66,48,96,94,59,161,175,
        155,225,124,250,173,124,123,194,199,153,211,105,181,204,249,154,183,91,233,163,218,222,135,237,158,
        61,120,71,129,202,184,74,57,245,117,74,24,216,78,49,147,163,77,82,167,56,207,78,94,68,228,185,163,
        191,53,238,253,235,244,183,221,222,55,248,163,240,151,226,206,169,171,124,41,215,60,85,224,61,107,
        84,214,160,159,76,212,124,43,54,179,108,247,215,49,152,153,166,137,173,183,249,185,17,110,99,242,
        229,84,110,227,25,175,198,95,219,87,254,8,163,166,252,30,240,163,124,74,248,119,241,155,225,93,231,
        194,29,82,109,186,126,163,226,159,21,90,233,113,196,92,176,72,82,253,207,217,46,126,101,101,13,189,
        24,149,193,82,65,53,245,247,197,31,248,34,135,143,252,75,241,19,246,162,241,135,135,124,127,164,
        232,94,39,248,233,170,152,52,57,124,249,141,158,139,165,94,89,67,167,234,19,79,8,131,123,95,11,99,
        117,228,121,114,170,7,120,203,50,224,215,15,225,191,248,33,31,197,239,129,183,26,42,248,79,197,127,
        10,252,85,163,252,63,212,124,72,124,27,163,234,118,247,58,53,182,141,103,226,27,56,86,241,237,55,
        67,168,45,141,213,157,228,79,45,187,20,187,73,18,234,85,117,143,0,31,180,205,50,92,38,97,21,28,76,
        111,109,154,209,175,159,249,159,204,156,7,226,119,16,112,125,121,214,201,42,242,169,219,154,18,92,
        208,149,182,186,125,87,116,211,182,151,177,242,239,195,255,0,248,34,134,173,225,189,79,194,186,135,
        198,239,139,159,8,190,15,248,71,197,82,162,233,151,55,126,41,180,150,243,93,220,21,130,88,134,101,
        130,86,100,101,33,132,141,128,234,118,176,56,175,218,47,217,222,63,131,191,179,14,153,162,124,16,
        240,95,136,188,35,166,234,94,31,128,197,7,134,198,179,110,218,195,146,190,116,146,201,6,239,53,228,
        112,198,87,98,188,239,45,192,175,129,39,255,0,130,25,124,96,248,123,225,93,29,116,109,83,246,122,
        248,169,173,234,223,11,151,225,190,186,254,60,240,177,179,179,240,230,46,239,110,68,250,52,54,112,
        152,146,5,23,166,51,110,99,139,204,54,209,72,92,51,50,139,255,0,5,255,0,224,223,223,21,124,21,253,
        168,124,7,227,9,188,113,225,255,0,27,120,87,192,190,36,240,158,161,253,149,170,44,182,179,106,81,
        232,190,25,131,72,143,81,50,199,27,75,21,228,55,48,153,162,183,19,61,180,145,191,151,41,202,134,
        168,202,178,28,30,94,159,213,227,171,221,189,89,211,199,222,44,113,31,24,202,11,57,170,157,56,107,
        24,65,114,193,61,175,109,91,118,210,237,182,150,138,215,103,255,217
    };
    // resources/fanuc.png
    const unsigned char fanuc_png[748] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,2,0,0,0,252,24,237,163,0,0,0,3,
        115,66,73,84,8,8,8,219,225,79,224,0,0,0,9,112,72,89,115,0,0,14,116,0,0,14,116,1,107,36,179,214,0,
        0,2,143,73,68,65,84,72,199,237,149,205,75,84,81,24,198,159,247,156,123,231,142,163,205,56,137,165,
        9,13,161,208,162,69,65,69,48,65,81,161,139,200,90,68,139,64,104,209,170,127,32,168,136,86,5,173,
        250,23,138,220,184,72,41,92,180,40,193,168,100,232,3,204,172,20,178,36,163,212,153,146,156,102,238,
        215,123,222,22,243,165,125,64,27,91,196,156,213,123,159,251,114,126,156,243,188,207,189,20,204,164,
        177,150,75,97,141,87,29,80,7,212,1,255,0,96,85,43,145,154,74,37,5,160,74,85,173,171,109,127,122,
        85,214,127,2,136,64,217,160,10,78,2,136,129,118,96,92,136,128,44,104,13,246,0,129,213,8,227,129,
        44,24,31,16,64,65,59,224,34,136,160,163,0,96,124,136,169,97,84,117,247,194,156,228,50,38,251,152,
        23,30,112,113,81,64,200,62,98,138,65,217,240,179,178,244,154,237,4,172,56,62,223,103,118,101,105,
        194,64,1,26,236,74,118,204,216,9,232,36,114,25,254,242,148,209,32,218,169,29,180,236,129,78,98,242,
        106,152,57,29,124,28,49,179,183,76,126,94,222,222,224,219,39,252,15,3,172,59,48,55,40,131,221,97,
        110,66,168,149,250,251,252,236,51,25,61,22,232,8,148,131,229,41,25,62,238,163,5,253,73,247,197,21,
        243,252,66,56,208,230,229,115,70,89,101,70,205,100,39,1,39,169,204,58,82,173,104,59,172,51,151,194,
        244,25,251,205,53,134,130,213,132,77,77,184,119,192,7,16,7,89,235,208,208,82,186,117,104,7,9,208,
        228,69,238,234,181,14,61,177,123,38,156,189,215,237,194,180,84,111,187,102,178,9,17,219,76,91,186,
        201,228,213,167,161,48,10,68,58,145,123,111,150,199,5,10,177,46,218,118,86,143,246,248,49,16,23,
        1,3,106,7,25,68,54,80,0,1,253,197,20,185,95,65,141,178,126,191,5,193,80,220,75,29,81,74,144,74,235,
        177,83,65,103,159,254,54,37,169,147,214,244,57,175,8,217,120,80,249,140,225,148,151,220,161,222,
        221,225,221,151,173,173,231,245,77,114,11,187,132,61,179,248,82,122,199,35,18,86,134,45,152,73,151,
        76,254,62,43,0,26,83,4,141,249,187,220,126,84,145,69,225,178,44,141,75,172,131,220,5,105,222,174,
        12,35,247,144,91,247,105,68,145,127,101,188,5,137,239,84,78,140,194,2,116,2,217,17,38,141,230,61,
        74,133,196,94,121,144,168,244,203,44,49,0,152,0,4,232,24,216,5,12,160,160,34,16,6,41,176,7,82,208,
        81,112,17,0,200,6,41,72,0,225,114,118,148,243,155,49,181,170,169,49,65,45,38,97,1,84,202,155,1,187,
        43,146,101,16,22,202,61,198,175,136,149,189,74,157,68,171,178,86,243,96,165,90,171,105,181,127,43,
        30,233,23,99,137,234,95,211,58,160,14,248,79,1,63,0,115,221,34,249,43,183,86,165,0,0,0,0,73,69,78,
        68,174,66,96,130
    };
    // resources/folder.png
    const unsigned char folder_png[684] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,6,0,0,0,115,122,122,244,0,0,0,
        4,115,66,73,84,8,8,8,8,124,8,100,136,0,0,2,99,73,68,65,84,88,195,237,151,77,75,21,81,24,199,127,
        227,189,51,247,69,205,133,144,25,133,68,214,210,162,133,45,236,141,218,69,237,111,244,1,106,45,212,
        34,225,134,129,183,207,112,191,65,181,22,90,68,32,185,117,147,182,74,8,77,163,68,28,28,157,59,103,
        206,204,60,51,45,210,208,238,232,194,60,186,168,3,3,7,14,103,158,223,252,255,207,243,204,57,86,150,
        101,28,231,232,224,152,199,127,128,226,65,55,54,27,181,191,10,252,232,217,171,189,1,154,141,218,
        77,96,106,159,253,207,129,23,38,21,168,95,187,114,134,129,211,61,109,11,74,39,204,125,94,29,159,
        95,116,57,12,136,189,114,224,118,79,151,195,250,134,106,123,180,142,25,232,239,6,24,55,162,64,179,
        81,171,247,245,86,113,189,96,223,141,125,189,85,86,214,130,131,52,145,93,246,89,59,27,81,179,81,
        171,47,127,157,31,31,185,122,153,66,193,58,244,140,23,201,88,252,222,138,30,143,189,46,109,199,221,
        165,64,75,69,245,82,103,63,51,159,86,140,149,93,181,226,72,174,5,47,159,222,159,24,26,186,84,184,
        126,235,6,93,93,221,70,130,251,254,38,211,83,31,42,141,39,241,4,48,182,11,192,130,209,145,225,65,
        42,225,44,18,154,249,250,10,48,50,60,200,220,236,199,209,54,128,142,2,158,248,75,101,169,218,70,
        59,159,4,75,116,20,240,218,171,32,203,220,64,233,190,178,109,182,59,7,74,67,150,185,57,101,152,173,
        5,42,226,68,103,201,40,64,24,198,64,182,222,6,32,34,110,16,68,136,136,81,0,191,165,17,145,213,118,
        128,68,188,48,212,36,73,106,88,1,141,36,210,158,3,137,164,174,31,196,36,137,97,5,130,152,68,82,55,
        223,2,165,73,196,172,2,65,168,17,201,81,64,68,60,165,35,227,22,168,48,66,68,220,28,11,196,245,3,
        125,4,22,104,146,60,0,17,241,148,210,36,134,171,64,169,61,44,72,37,93,109,5,17,177,241,28,136,73,
        115,147,48,77,61,165,35,196,176,5,129,210,72,186,3,192,113,28,0,235,225,189,139,94,217,41,26,175,
        2,165,34,54,91,218,115,28,199,2,178,226,175,31,33,61,147,83,11,231,30,220,189,64,160,52,142,83,52,
        18,60,138,18,66,29,241,118,122,241,20,224,1,173,223,0,158,31,157,255,178,188,241,254,205,228,204,
        29,147,10,44,253,240,223,185,158,30,0,190,1,129,101,219,182,5,148,129,179,192,73,160,180,117,88,
        205,182,224,200,153,239,56,70,228,174,239,60,207,101,127,204,99,192,5,22,128,150,101,219,246,246,
        139,172,35,188,41,101,64,10,100,214,63,127,59,254,9,184,250,82,212,32,166,215,192,0,0,0,0,73,69,
        78,68,174,66,96,130
    };
    // resources/information.png
    const unsigned char information_png[741] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,2,156,73,68,65,84,56,203,165,147,203,107,212,87,28,197,63,
        119,76,172,100,76,38,49,10,153,137,54,143,209,168,40,104,161,137,82,44,8,197,77,33,82,59,84,65,162,
        46,92,116,149,109,21,92,249,31,8,10,62,86,190,176,165,116,154,174,133,90,154,148,134,206,162,27,
        153,198,48,213,196,52,143,209,24,51,201,36,253,205,220,239,189,247,235,66,72,124,180,27,61,203,47,
        95,62,28,56,231,24,85,229,125,84,243,230,33,115,117,52,45,193,29,87,23,78,86,173,180,56,13,40,161,
        8,225,166,119,225,206,224,217,79,30,190,250,111,94,117,240,197,149,145,140,181,114,177,35,161,201,
        158,182,70,26,214,174,1,96,33,114,12,21,158,112,127,122,121,6,163,253,185,243,159,101,223,2,28,190,
        156,207,216,72,110,28,218,86,23,223,221,90,207,212,156,165,184,16,225,131,146,168,91,67,42,177,142,
        194,179,50,3,63,63,92,166,134,83,185,11,135,179,43,128,222,75,247,59,69,220,208,161,173,241,212,
        246,150,122,114,99,37,156,19,246,180,53,129,42,127,142,205,99,98,134,93,201,245,252,51,95,230,167,
        187,133,105,52,124,154,187,118,244,81,12,64,130,235,235,104,208,212,142,100,3,195,133,231,216,200,
        34,213,64,239,199,73,122,187,83,136,19,108,213,146,159,44,209,190,49,65,215,214,134,148,70,210,7,
        16,3,176,222,159,216,215,222,204,88,113,9,17,65,130,199,7,199,143,195,19,100,135,39,176,98,177,206,
        178,20,69,140,207,46,114,96,111,27,198,218,19,43,41,216,200,182,54,213,215,80,152,41,225,188,71,
        188,160,33,208,119,176,19,5,134,71,166,209,16,0,67,113,110,145,174,212,102,212,71,173,171,14,170,
        22,13,138,83,176,174,74,240,158,16,148,252,227,121,254,173,56,188,117,120,241,56,113,56,43,168,1,
        188,103,5,0,126,106,110,185,66,115,188,22,163,49,52,40,193,123,94,38,164,120,113,4,17,130,88,18,
        241,15,120,178,88,198,152,48,181,10,176,238,214,96,126,146,182,77,113,8,1,156,114,100,127,59,59,
        63,108,162,110,93,45,253,71,246,32,34,56,17,58,90,18,12,13,253,13,232,173,213,38,86,162,219,35,15,
        202,95,167,147,141,169,158,174,77,252,150,159,228,251,95,71,249,246,222,95,168,56,84,3,138,242,209,
        246,45,140,151,22,121,148,47,76,27,184,253,90,145,186,79,127,151,209,114,229,198,231,95,238,142,
        119,110,172,231,193,227,89,102,159,151,9,46,176,161,177,142,109,91,154,25,47,45,113,239,135,95,150,
        49,181,167,114,3,223,100,223,170,114,247,177,235,25,212,94,76,239,74,38,15,236,75,211,188,126,45,
        160,60,93,168,48,248,251,40,19,249,194,140,49,177,254,220,192,153,236,127,110,1,160,231,171,43,105,
        85,127,28,13,39,9,149,22,52,96,140,41,2,55,13,114,231,143,129,115,255,63,166,119,209,11,168,63,130,
        123,89,182,33,185,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/logo_md.png
    const unsigned char logo_md_png[3467] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,98,0,0,0,42,8,6,0,0,0,72,174,142,15,0,0,0,6,
        98,75,71,68,0,0,0,0,0,0,249,67,187,127,0,0,0,9,112,72,89,115,0,0,46,35,0,0,46,35,1,120,165,63,118,
        0,0,13,43,73,68,65,84,120,94,237,154,119,84,149,71,22,192,179,155,93,53,27,79,118,79,140,134,68,
        37,24,65,68,138,20,169,22,154,137,72,20,209,16,1,187,66,108,32,88,0,11,42,210,145,14,210,17,16,41,
        130,34,8,136,5,20,4,20,11,29,177,34,85,120,210,65,122,243,205,206,253,240,219,125,190,60,152,151,
        200,121,57,57,231,253,241,59,192,55,247,222,111,102,238,204,189,119,230,227,19,132,208,39,124,254,
        124,136,2,124,120,3,81,128,15,111,32,10,240,225,13,68,1,62,188,129,40,192,135,55,16,5,248,240,6,
        162,192,159,193,224,224,224,100,146,204,192,192,192,20,38,147,73,180,245,87,129,40,192,74,102,118,
        174,142,130,218,138,38,93,131,45,21,70,38,7,50,29,221,188,188,42,42,171,196,73,122,99,209,223,215,
        249,101,69,249,181,13,213,47,178,116,155,26,202,20,134,135,250,167,192,243,186,122,198,119,59,246,
        154,223,214,209,223,252,116,147,241,222,210,13,70,187,41,54,26,237,41,53,220,190,171,84,107,173,
        126,197,213,27,233,134,180,157,142,214,26,145,186,202,60,173,151,143,175,234,55,53,148,43,178,190,
        227,230,237,44,61,220,231,198,117,27,183,191,220,177,119,255,189,93,102,22,89,123,246,91,222,222,
        101,110,145,105,108,122,32,87,127,219,206,199,202,154,43,25,54,142,167,195,73,253,165,121,88,80,
        164,170,170,181,166,86,111,243,142,39,187,247,91,222,116,241,244,117,171,120,245,199,231,1,32,10,
        176,242,168,176,120,153,174,225,214,124,41,37,85,52,123,190,52,18,18,151,67,98,139,22,51,111,101,
        229,172,35,233,114,130,81,87,180,52,208,65,18,249,158,248,30,5,57,201,160,216,128,85,141,197,247,
        35,142,65,91,201,227,39,10,115,36,228,208,92,41,121,252,142,37,240,30,180,64,126,9,154,38,40,138,
        78,57,185,133,130,76,51,163,92,49,57,202,40,47,204,125,49,242,61,41,140,188,172,5,81,86,170,77,28,
        235,59,178,239,230,105,235,232,111,42,84,211,214,237,152,57,79,10,205,151,85,65,162,50,202,104,190,
        220,98,36,40,38,131,100,151,104,162,159,244,54,148,122,7,4,187,144,250,75,83,82,86,174,180,234,151,
        77,37,18,138,203,208,76,209,133,212,60,204,151,83,97,94,207,184,109,64,210,29,11,162,0,39,90,90,
        219,166,109,217,105,122,87,92,97,41,130,206,96,199,48,223,52,54,125,75,210,227,4,236,138,23,101,
        169,219,162,253,180,58,131,177,51,252,237,196,208,157,52,219,24,104,75,184,114,213,88,80,76,26,41,
        170,107,81,128,51,180,127,222,80,13,109,111,234,10,53,66,79,43,32,208,1,238,222,116,9,105,111,169,
        20,99,50,223,113,124,15,132,177,35,54,246,209,243,100,148,40,91,146,138,170,104,245,250,77,47,218,
        218,219,191,36,245,113,44,240,60,124,101,100,178,255,54,204,3,216,131,133,82,247,186,94,136,164,
        199,9,162,192,88,56,186,121,7,125,47,185,8,41,105,172,68,130,11,100,208,239,217,218,156,232,104,
        173,22,61,231,165,214,23,225,177,20,249,217,138,161,242,252,232,35,240,220,112,251,238,66,152,60,
        28,94,16,188,175,160,228,137,226,187,225,174,47,34,60,85,7,195,220,84,80,144,163,52,42,200,13,118,
        32,217,7,158,62,127,41,45,42,171,76,217,154,35,177,8,249,135,132,219,147,116,72,248,6,134,58,131,
        45,152,7,216,25,86,39,236,46,146,116,56,65,20,224,68,95,127,255,100,181,149,186,109,194,11,21,169,
        65,201,44,214,64,242,170,63,14,189,237,234,250,130,164,59,30,21,79,110,108,14,116,144,66,216,33,
        8,86,251,80,127,235,140,151,149,117,194,224,136,239,22,200,34,11,107,219,75,32,151,145,104,145,14,
        187,0,100,82,162,141,11,73,118,105,170,106,106,133,23,42,171,163,69,203,126,192,78,149,71,49,23,
        47,155,145,116,198,99,100,100,228,111,43,215,25,212,131,45,121,60,15,114,75,151,227,185,208,100,
        182,182,182,77,39,233,178,67,20,224,68,194,149,84,99,136,175,86,199,237,226,96,80,176,26,96,162,
        240,192,246,145,116,73,92,139,223,151,27,226,178,8,133,56,203,161,155,9,251,179,224,217,161,99,167,
        18,33,39,117,245,12,78,106,174,47,80,31,117,150,58,118,132,34,106,111,169,154,79,178,73,83,89,93,
        35,2,142,128,9,155,43,165,128,98,47,38,126,148,35,210,51,239,172,155,133,115,196,193,163,39,47,227,
        112,55,162,132,67,30,204,67,232,185,168,99,36,93,118,136,2,156,88,165,183,177,6,87,13,29,184,132,
        252,39,172,8,73,156,188,33,126,227,202,228,5,73,151,196,219,246,215,115,32,228,192,174,128,9,111,
        170,207,215,172,126,221,34,16,115,49,201,20,218,227,131,215,49,32,57,67,219,163,59,254,30,36,123,
        172,96,71,204,163,119,196,123,71,152,147,116,198,3,42,56,28,13,134,251,250,250,39,227,177,63,151,
        80,88,134,196,229,151,66,242,175,35,233,178,67,20,96,7,87,12,10,95,124,59,23,249,133,132,81,241,
        213,227,76,128,59,196,70,72,128,34,56,84,65,59,201,6,137,162,123,97,182,1,184,154,10,199,19,126,
        33,112,77,19,203,115,59,112,0,60,143,11,210,109,28,25,25,250,7,201,22,43,19,233,136,87,149,213,243,
        161,130,115,116,247,14,132,191,3,207,158,179,161,231,1,42,189,188,135,249,26,36,27,172,16,5,216,
        217,127,248,120,26,108,199,166,230,102,1,248,187,186,182,110,46,84,13,56,71,80,201,20,87,38,23,72,
        54,72,64,229,115,41,116,125,77,152,155,50,10,116,92,136,10,239,134,218,117,119,50,102,211,59,5,18,
        52,62,55,104,147,236,176,51,145,142,176,113,116,61,63,125,142,24,130,241,195,223,140,198,198,153,
        210,42,234,76,218,182,185,149,245,85,146,13,86,136,2,172,224,114,109,58,84,72,38,135,142,100,176,
        62,223,190,199,60,111,30,174,205,113,162,162,146,118,231,219,183,255,38,217,34,193,168,45,84,133,
        179,69,36,206,5,81,190,63,188,195,33,169,49,194,115,25,46,85,101,209,237,228,99,41,36,125,78,76,
        148,35,186,123,122,62,135,179,200,150,157,38,5,172,207,247,30,60,124,83,68,90,145,202,65,210,42,
        26,204,166,230,150,175,73,182,104,136,2,172,4,158,141,176,157,42,48,7,61,204,47,84,101,125,126,245,
        70,134,33,93,194,65,178,138,138,187,244,135,6,200,78,118,154,93,44,172,254,243,62,154,8,156,112,
        206,83,21,118,196,96,111,79,235,239,174,74,128,137,114,68,76,124,130,217,103,51,4,17,62,200,174,
        97,125,158,153,157,187,26,42,40,106,30,196,101,81,80,88,228,9,146,45,26,162,0,13,148,106,202,154,
        218,93,203,87,235,53,178,183,245,15,12,76,90,166,165,243,118,161,178,26,90,128,79,193,107,13,183,
        86,144,236,113,195,240,80,255,228,132,48,131,87,144,19,206,251,44,135,42,137,89,249,236,150,62,73,
        111,44,38,202,17,63,232,252,242,6,79,118,55,204,201,7,253,29,30,254,251,114,29,189,102,40,94,36,
        112,184,134,66,134,219,251,48,162,0,205,173,172,108,93,88,5,145,177,241,135,56,181,59,184,122,5,
        193,149,4,36,43,56,95,20,150,148,170,144,108,114,195,149,243,219,75,33,87,192,174,56,235,170,244,
        142,81,87,164,74,210,25,139,137,112,4,68,131,169,2,66,232,76,240,89,39,78,237,158,126,65,174,116,
        210,134,156,153,147,247,96,5,201,38,64,20,160,193,165,90,49,30,68,247,88,237,173,109,237,211,164,
        148,213,134,70,7,41,143,44,143,219,38,144,108,146,120,144,233,227,27,132,147,53,236,6,200,21,225,
        248,212,29,227,175,221,54,56,208,61,149,164,203,137,137,112,196,46,179,67,153,34,210,74,131,120,
        55,112,108,239,233,237,253,12,231,136,126,200,19,194,11,21,16,228,13,146,77,128,40,0,188,124,85,
        41,6,7,56,131,109,59,203,175,165,223,218,144,114,237,198,54,118,210,110,102,108,92,161,171,223,180,
        80,69,157,186,72,195,29,25,6,231,144,108,143,5,172,124,56,61,71,122,107,208,9,123,40,210,91,157,
        186,28,204,76,57,158,72,210,231,196,199,58,162,158,193,152,13,147,171,107,176,181,234,122,250,237,
        245,120,220,155,216,193,243,163,191,234,151,141,181,120,81,82,73,27,126,114,115,15,71,124,57,96,
        231,226,30,6,37,43,28,218,4,132,37,56,242,141,136,36,149,31,96,144,202,239,147,85,120,84,172,37,
        201,54,39,32,55,92,8,92,221,68,223,37,221,75,119,13,110,106,120,172,0,39,110,112,12,156,37,94,61,
        189,185,145,100,135,157,143,117,4,14,59,238,179,68,165,168,155,219,175,191,23,199,44,248,45,115,
        197,225,38,150,114,130,178,230,232,60,248,135,132,219,145,108,19,95,222,221,221,51,117,129,252,146,
        145,159,55,237,40,47,127,250,76,97,60,138,74,203,150,44,91,161,211,5,187,66,92,126,9,210,209,223,
        92,69,178,207,137,236,107,246,209,16,146,194,221,151,160,232,51,90,29,136,57,72,29,220,30,100,122,
        251,130,19,168,10,202,75,109,160,183,155,251,242,16,248,24,71,12,224,130,4,235,245,105,173,53,168,
        45,46,125,172,132,81,124,255,147,29,197,130,226,18,21,92,212,180,72,41,169,81,183,211,63,174,89,
        223,200,158,216,217,33,118,0,238,143,166,76,159,141,174,94,79,231,106,5,58,185,123,251,253,255,132,
        169,128,30,228,23,170,145,116,88,169,126,145,245,51,76,54,181,242,177,51,26,95,23,104,116,118,245,
        79,129,239,19,208,14,85,20,78,218,40,216,89,14,93,139,223,151,67,178,199,202,199,56,34,57,237,250,
        150,207,166,11,162,216,75,137,166,36,89,192,39,48,212,17,118,3,148,178,144,180,51,115,238,174,26,
        79,158,104,80,107,173,126,3,142,249,3,253,253,253,196,207,151,0,12,22,118,3,156,180,97,176,7,143,
        158,188,66,210,161,233,235,109,159,22,233,173,217,11,87,225,224,140,188,12,183,16,120,126,224,168,
        77,210,226,229,63,117,194,239,237,205,21,146,161,46,242,8,242,69,128,189,4,42,47,136,59,72,178,203,
        210,183,15,46,253,46,92,76,226,250,146,18,71,132,231,240,17,172,243,45,119,55,204,140,55,141,51,
        113,57,207,148,195,78,135,67,222,46,51,139,204,241,228,199,53,118,255,81,129,250,127,102,9,163,163,
        167,28,226,73,47,102,101,235,78,211,135,162,178,42,72,22,15,24,59,113,164,181,173,237,43,146,14,
        112,35,225,96,70,176,179,44,130,114,53,46,120,109,61,60,203,47,42,91,12,43,10,114,212,185,152,120,
        11,120,86,156,23,97,3,78,128,235,14,216,29,29,109,53,243,72,182,129,170,154,90,17,72,158,244,53,
        120,116,124,2,87,59,162,172,252,169,220,116,33,49,180,207,226,40,87,21,16,205,158,3,86,25,112,133,
        15,239,131,16,85,223,192,16,28,75,118,92,67,198,166,7,238,124,41,56,15,101,229,220,27,119,91,177,
        3,247,252,116,120,18,194,103,11,47,255,96,87,146,78,233,195,168,195,16,138,168,187,36,39,105,212,
        218,248,108,17,19,63,199,177,150,1,69,128,12,174,196,240,106,30,102,188,175,64,82,162,140,139,224,
        186,3,28,145,16,102,248,156,155,11,192,162,146,50,21,88,157,163,31,153,228,145,135,111,0,87,183,
        183,230,86,199,83,96,65,166,114,25,158,105,82,210,110,108,17,122,127,182,130,155,7,123,87,207,160,
        177,100,57,62,236,235,235,159,18,118,62,198,18,14,102,112,167,2,191,247,246,246,253,235,221,59,206,
        159,33,89,129,143,67,167,156,220,66,232,79,146,176,43,240,4,142,228,230,61,248,17,235,255,38,97,
        225,10,105,82,81,94,184,53,84,68,144,156,253,237,196,209,147,162,209,43,18,23,207,51,190,80,54,67,
        156,5,160,63,91,119,153,222,163,250,216,219,54,3,159,41,154,32,87,128,110,74,244,175,247,219,91,
        170,68,57,245,9,78,183,56,84,204,218,182,123,95,54,84,126,208,47,105,21,13,164,186,82,183,185,20,
        231,158,161,161,161,79,57,233,65,130,198,57,97,15,220,163,193,120,252,130,195,108,123,122,122,63,
        231,102,30,224,62,202,213,219,207,131,158,7,106,87,224,211,54,62,24,175,193,137,251,239,236,242,
        108,47,30,156,244,147,222,198,26,8,43,95,9,205,167,188,8,135,179,111,113,105,42,137,183,22,30,196,
        200,110,115,203,12,118,35,192,157,220,123,218,184,108,27,130,239,182,223,8,75,82,49,24,116,161,238,
        158,45,38,141,159,73,192,239,239,18,146,82,140,169,142,190,109,154,153,28,101,244,8,42,32,159,19,
        115,168,120,143,29,49,244,180,232,178,9,180,95,184,148,180,23,86,33,236,44,176,51,138,2,250,252,
        107,33,28,42,29,207,15,13,51,63,233,234,108,16,74,60,183,185,24,118,18,252,243,0,84,90,177,1,171,
        170,158,21,39,238,161,251,133,107,251,205,120,23,140,128,254,12,92,94,130,51,71,251,165,72,125,248,
        135,127,40,128,191,225,227,14,173,3,21,206,186,13,219,159,129,3,224,134,117,180,15,10,212,60,64,
        136,129,42,114,203,78,211,60,78,243,0,255,96,129,101,6,225,70,26,198,76,207,3,252,132,69,37,128,
        203,91,252,59,19,135,217,15,114,219,7,70,134,135,135,63,181,113,116,13,55,179,60,118,217,193,213,
        43,216,205,199,223,199,221,55,192,203,197,211,215,255,184,157,115,244,78,179,67,201,1,161,17,182,
        156,58,0,223,131,127,221,119,48,245,136,141,67,28,174,156,2,41,93,31,127,47,140,55,232,159,116,60,
        125,206,216,100,127,42,206,59,212,61,125,79,119,139,192,173,43,71,147,210,19,45,211,114,174,59,68,
        150,220,143,180,234,234,104,16,130,182,234,218,58,97,171,19,118,209,214,118,78,145,118,167,61,34,
        240,57,230,127,156,114,118,139,48,183,178,190,156,115,239,254,74,250,221,248,76,161,159,119,203,
        221,47,51,197,58,41,45,206,228,58,124,114,165,219,242,241,196,24,225,247,90,227,254,59,123,248,4,
        176,245,203,15,239,222,8,220,239,100,124,230,57,76,235,192,138,199,227,15,52,57,120,36,209,193,213,
        51,132,158,135,211,94,103,252,142,219,59,71,237,54,183,72,134,171,12,78,243,128,11,2,81,220,158,
        122,248,164,125,188,163,155,87,144,155,183,159,47,235,60,216,56,185,70,24,153,28,72,201,202,253,
        48,220,255,198,208,95,9,110,47,212,254,10,16,5,248,240,6,162,0,31,222,64,20,224,195,27,136,2,124,
        120,3,81,128,15,111,32,10,240,225,13,68,1,62,188,129,40,192,135,55,16,5,248,240,134,255,2,18,255,
        254,13,227,100,132,202,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/magnifier.png
    const unsigned char magnifier_png[578] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,249,73,68,65,84,56,203,165,146,191,107,147,97,16,199,191,
        239,143,36,70,172,169,154,164,16,131,63,232,80,245,15,16,42,66,160,69,112,200,212,173,32,14,130,
        56,84,119,221,186,8,142,14,166,131,139,139,210,77,4,59,84,69,33,34,136,154,65,208,198,86,208,68,
        11,49,209,216,10,38,111,222,231,121,238,158,115,176,86,36,121,149,226,103,185,155,62,247,189,227,
        28,17,193,255,224,255,106,30,215,216,181,214,150,136,165,200,204,57,98,11,67,220,32,226,5,99,120,
        102,122,60,109,7,9,28,17,65,185,198,174,101,251,40,149,144,194,174,237,14,124,87,0,1,66,18,172,182,
        67,124,252,210,43,27,162,137,179,147,249,62,137,11,0,204,182,180,51,97,11,217,29,14,66,195,104,119,
        24,173,14,35,208,22,7,50,73,100,83,177,130,210,84,26,148,192,5,0,34,46,238,78,58,248,174,24,129,
        22,144,21,48,11,186,90,176,214,99,236,221,147,132,210,84,140,20,24,226,156,231,2,129,22,176,21,176,
        197,79,137,21,116,149,69,60,230,65,107,202,69,30,81,27,130,149,24,200,10,172,5,88,126,87,177,0,11,
        160,12,33,50,129,214,212,8,141,133,239,58,27,147,177,89,99,190,131,32,52,32,173,63,71,11,12,45,212,
        91,1,134,18,46,226,158,3,222,72,146,240,29,12,39,61,188,126,215,198,72,247,229,240,195,203,197,177,
        129,2,165,105,166,214,236,148,151,62,124,67,204,3,178,67,62,178,41,31,113,87,240,188,218,68,231,
        107,19,147,185,214,54,165,130,39,119,46,30,27,235,251,3,0,184,122,247,189,107,136,74,198,112,81,
        19,231,200,48,12,241,167,116,111,73,79,164,94,29,204,31,62,138,198,202,11,188,173,220,111,27,19,
        30,63,117,237,205,202,31,130,40,22,103,79,196,181,14,231,211,251,14,77,237,63,50,142,213,229,103,
        168,86,238,181,207,92,175,103,54,87,248,27,39,103,31,104,165,130,233,122,245,233,237,229,202,34,
        178,249,81,104,173,210,125,43,252,139,27,231,70,227,68,106,222,139,37,166,130,206,250,149,243,55,
        215,46,109,73,0,0,115,167,51,30,51,141,92,184,181,222,216,114,130,40,126,0,74,184,55,161,170,50,
        203,161,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/magnifier_zoom_in.png
    const unsigned char magnifier_zoom_in_png[645] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,2,60,73,68,65,84,56,203,165,145,77,72,84,81,20,199,255,243,
        222,124,52,126,244,114,26,53,108,72,212,133,213,54,10,172,160,152,136,90,184,114,39,68,68,16,9,86,
        180,9,114,231,50,218,20,152,5,109,138,40,164,22,17,228,194,10,140,105,81,100,3,17,226,164,17,205,
        168,53,89,154,99,206,204,155,251,238,61,231,222,22,145,37,142,133,244,219,156,179,250,157,255,57,
        199,103,140,193,255,224,255,213,60,75,179,165,181,238,39,54,237,204,220,64,172,161,136,179,68,60,
        168,20,119,119,182,69,117,57,129,207,24,131,68,154,45,205,122,216,9,153,125,53,21,62,248,45,3,24,
        64,144,193,244,156,192,212,108,41,161,136,226,39,14,196,116,89,193,240,123,117,205,9,233,174,250,
        42,11,121,143,33,148,1,27,32,96,1,213,33,27,125,163,103,81,20,139,144,66,137,155,29,119,195,127,
        10,44,0,32,226,246,72,216,135,188,199,112,165,1,105,3,102,131,162,52,152,47,49,242,238,2,226,181,
        173,40,21,197,186,178,55,80,196,13,182,101,193,149,6,172,13,180,1,88,27,220,75,159,67,190,152,67,
        125,160,10,121,207,197,198,64,5,14,93,218,111,164,144,185,167,61,207,35,75,9,164,34,104,131,159,
        147,245,239,250,125,241,27,246,68,155,16,171,112,176,88,42,96,179,83,141,157,205,141,40,21,69,205,
        178,4,82,82,86,40,29,243,91,62,184,164,151,18,216,170,18,131,169,215,136,4,195,136,69,28,140,77,
        126,196,212,167,89,72,161,196,114,129,162,193,204,23,183,171,121,83,37,136,13,138,82,67,107,224,
        216,142,62,108,8,219,56,115,43,142,245,97,27,153,169,175,72,94,124,227,91,113,68,79,82,119,122,166,
        144,24,155,92,64,192,6,234,170,253,168,115,252,8,90,6,35,169,25,104,207,143,196,200,56,66,30,233,
        7,231,119,183,174,120,35,0,92,126,248,193,82,68,253,74,113,187,36,110,32,197,80,196,159,163,165,
        49,25,119,70,155,98,219,118,33,59,241,10,239,146,143,231,148,18,123,143,92,121,59,177,76,176,26,
        67,189,7,131,82,138,129,232,150,173,29,141,219,219,48,61,254,18,169,228,163,185,227,215,51,181,75,
        43,252,141,195,189,79,164,231,185,157,153,212,139,251,227,201,33,212,197,90,32,165,23,93,177,194,
        191,184,113,178,37,72,228,13,216,129,80,135,91,200,93,56,117,123,190,103,77,2,0,184,122,180,214,
        102,166,250,211,119,114,217,53,39,88,141,31,184,135,79,39,97,137,85,205,0,0,0,0,73,69,78,68,174,
        66,96,130
    };
    // resources/page_paste.png
    const unsigned char page_paste_png[677] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,2,92,73,68,65,84,56,203,117,147,63,136,149,71,20,197,127,
        119,230,219,231,91,86,93,93,4,55,226,106,34,168,171,40,72,36,218,248,167,48,133,205,90,4,108,172,
        132,132,24,44,172,44,130,32,90,218,41,164,81,176,136,8,18,193,72,138,104,99,147,96,20,20,132,128,
        136,144,136,219,69,113,77,220,200,123,190,124,111,102,238,73,241,189,85,113,245,52,211,204,28,126,
        231,204,189,38,9,128,115,95,125,178,17,120,192,124,253,123,232,252,244,18,62,32,59,251,229,199,159,
        2,39,129,169,133,99,203,57,112,236,4,221,231,119,1,24,89,182,141,139,39,190,165,215,125,9,112,9,
        184,122,232,252,244,143,111,27,84,192,213,189,95,31,157,24,251,104,5,127,223,248,30,73,148,186,11,
        128,36,118,110,158,96,100,203,30,36,77,253,116,238,187,125,192,60,131,213,99,227,43,153,253,243,
        14,158,94,49,125,249,52,72,128,120,174,123,8,49,115,255,22,99,147,219,22,189,47,66,5,160,220,199,
        115,34,172,218,132,151,140,36,126,40,71,40,114,220,7,69,252,209,197,118,124,206,55,103,126,214,139,
        122,252,225,95,211,79,182,222,60,59,213,171,0,188,36,60,39,60,213,148,250,63,64,148,202,57,254,197,
        36,51,29,199,0,151,72,197,169,226,102,46,220,153,221,16,45,62,222,117,248,218,218,198,32,215,120,
        201,32,199,172,73,16,67,224,197,43,241,104,70,132,32,82,118,94,246,50,187,215,13,179,99,253,18,70,
        90,97,252,55,149,223,67,99,208,199,115,159,146,250,120,46,120,46,0,68,131,118,5,173,104,180,162,
        209,110,5,158,205,246,88,191,20,14,110,31,37,39,173,105,8,82,141,82,31,101,199,83,1,137,210,22,102,
        48,20,27,34,69,163,93,5,30,255,35,58,79,107,62,91,181,128,161,42,80,189,33,40,120,42,120,118,112,
        225,18,134,17,67,24,76,140,112,23,44,136,88,48,98,140,232,245,47,164,130,250,229,13,254,160,249,
        230,48,12,39,26,180,170,128,73,184,27,102,134,52,48,200,41,83,82,193,75,25,68,0,47,194,128,42,64,
        176,128,171,233,36,56,208,130,225,170,25,180,134,160,159,241,84,80,41,40,59,242,102,63,138,231,57,
        200,121,114,101,112,163,2,110,246,58,157,157,11,39,38,209,92,4,53,233,234,220,1,222,191,71,117,238,
        96,30,172,2,78,253,114,253,202,34,96,203,219,23,158,109,218,207,80,88,195,104,59,33,65,48,195,108,
        208,39,16,195,98,92,185,111,115,235,252,174,246,28,189,253,107,12,182,22,194,56,168,219,60,211,92,
        173,230,42,157,209,145,161,225,255,1,175,53,73,19,91,222,135,16,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/paste_plain.png
    const unsigned char paste_plain_png[568] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,239,73,68,65,84,56,203,141,146,63,104,83,81,20,198,127,
        47,47,134,148,38,37,104,193,127,212,63,184,21,4,73,68,72,160,147,179,162,32,8,46,29,44,20,146,185,
        32,46,21,92,164,139,171,66,55,65,112,176,8,78,46,5,17,58,72,3,14,58,8,98,7,39,75,69,106,105,109,
        222,187,231,124,14,201,139,105,19,193,3,151,123,134,251,253,206,247,29,110,36,9,128,167,115,231,
        167,129,79,12,215,246,252,242,70,133,127,84,244,228,238,185,42,240,0,184,86,58,122,156,59,247,23,
        217,221,122,15,192,248,228,21,158,45,222,227,247,238,47,128,231,192,202,252,242,198,203,65,64,30,
        88,185,122,227,230,153,177,82,153,244,235,7,36,97,157,93,0,36,49,115,113,138,220,201,11,72,186,245,
        230,213,235,235,192,16,224,236,88,105,130,100,103,147,224,129,141,23,143,65,2,196,150,218,8,177,
        191,249,141,226,228,233,2,80,56,28,33,15,128,27,10,129,92,229,4,110,1,201,15,230,220,223,35,217,
        222,27,185,131,60,128,220,241,16,240,180,131,167,157,158,131,255,171,30,32,224,150,246,39,187,34,
        62,254,152,96,223,98,80,119,23,138,10,124,63,50,77,171,213,90,114,119,204,12,51,251,220,3,24,30,
        82,176,128,155,145,132,28,241,216,36,183,231,30,146,36,201,225,161,11,146,136,227,56,109,54,155,
        75,125,0,33,69,230,40,56,110,194,205,233,116,58,172,173,173,161,129,72,89,95,175,215,9,33,240,215,
        129,57,30,28,15,134,91,132,153,1,80,173,86,15,8,179,94,210,32,192,241,212,80,112,20,12,183,28,222,
        19,180,219,237,190,120,16,82,175,215,49,179,46,160,59,189,11,240,44,2,134,164,145,14,178,234,59,
        192,132,167,222,219,129,33,139,240,40,0,176,190,190,62,36,148,68,163,209,232,59,120,151,38,201,204,
        248,169,41,228,66,238,228,83,136,127,150,145,68,173,86,27,18,103,119,6,120,244,118,117,181,12,92,
        202,30,25,121,118,42,151,41,22,139,68,81,52,242,3,197,113,140,153,17,141,202,54,59,59,155,51,179,
        5,51,59,214,251,48,253,227,238,131,231,203,31,69,122,100,107,137,17,144,55,0,0,0,0,73,69,78,68,174,
        66,96,130
    };
    // resources/plug-connect.png
    const unsigned char plug_connect_png[457] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,128,73,68,65,84,56,203,157,146,77,75,2,81,20,134,159,177,
        172,24,26,34,42,194,54,129,21,45,114,252,11,69,16,76,97,246,33,41,217,20,68,144,161,254,128,254,
        66,187,254,69,237,36,106,21,4,69,139,86,21,17,34,237,36,16,134,104,81,36,58,244,225,105,115,13,145,
        52,233,192,203,125,185,247,60,135,123,14,7,254,31,22,112,253,95,120,22,184,81,69,90,6,110,213,89,
        235,91,138,57,224,46,149,74,9,112,167,244,3,123,154,64,247,74,123,137,68,34,232,56,14,182,109,7,
        21,163,85,19,181,6,112,62,157,78,103,75,165,18,197,98,145,114,185,140,235,186,136,8,134,97,144,201,
        100,178,64,160,209,151,115,201,100,82,128,137,104,52,42,129,128,41,62,159,79,250,251,7,196,52,77,
        1,114,64,168,89,207,15,161,208,188,132,195,97,1,98,147,147,83,226,247,143,200,216,216,184,0,15,245,
        112,253,12,230,1,207,203,203,27,249,124,129,153,25,235,240,226,226,124,117,112,112,8,93,239,174,
        230,159,52,42,16,6,246,99,177,181,209,74,69,195,227,241,242,250,90,98,122,218,58,184,186,186,52,
        117,221,248,117,232,181,67,204,219,246,230,176,227,60,227,186,239,0,116,118,122,209,52,13,17,56,
        59,59,14,2,126,224,168,81,239,11,192,99,60,190,37,150,181,34,145,200,186,0,143,53,90,248,107,97,
        150,128,2,80,136,199,183,69,249,197,86,183,45,2,60,1,203,74,85,223,82,108,0,111,192,14,48,0,244,
        1,189,64,15,96,0,58,208,5,116,0,237,64,91,253,38,126,0,187,192,41,240,5,124,170,187,207,58,255,161,
        222,171,170,0,124,3,92,82,131,212,101,221,244,44,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/plug-disconnect.png
    const unsigned char plug_disconnect_png[505] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        115,66,73,84,8,8,8,8,124,8,100,136,0,0,1,176,73,68,65,84,56,203,149,211,205,75,148,81,24,5,240,223,
        235,232,24,65,68,20,33,180,41,104,33,81,168,145,184,116,21,163,125,160,46,20,193,164,112,210,157,
        8,78,45,164,22,45,107,213,127,33,180,24,92,52,209,218,149,27,65,44,107,33,217,135,131,160,129,232,
        34,230,157,24,199,219,230,45,6,116,154,58,112,120,30,30,184,231,158,123,30,110,202,255,161,15,175,
        176,137,203,73,255,207,232,199,202,204,204,76,192,74,194,254,166,6,135,110,225,93,194,23,211,211,
        211,157,187,187,187,178,217,108,39,82,136,162,6,2,31,114,185,220,149,82,169,36,142,99,113,28,43,
        151,203,170,213,170,214,214,86,249,124,254,99,170,129,192,230,210,210,210,141,238,238,238,179,123,
        123,123,74,165,146,74,165,34,157,78,91,88,88,88,199,227,70,2,235,248,182,188,188,220,211,213,213,
        117,38,142,99,81,20,41,20,10,159,49,139,66,189,12,174,226,73,210,191,198,236,252,252,252,102,58,
        157,22,66,128,230,100,126,52,101,60,196,211,68,164,22,67,216,206,100,50,1,219,199,221,186,58,53,
        53,21,176,138,201,58,206,70,16,39,245,8,214,6,6,6,195,240,240,72,192,26,110,39,243,107,120,86,47,
        164,223,33,222,65,166,173,237,194,185,173,173,109,29,29,29,231,55,54,62,93,71,21,61,200,227,251,
        113,2,77,184,139,151,227,227,15,218,15,14,130,40,106,182,191,255,67,111,239,205,118,228,176,131,
        247,245,28,68,248,50,49,49,121,177,88,220,17,199,63,65,75,75,51,130,195,195,96,113,241,237,87,92,
        250,219,174,7,81,28,27,203,134,190,190,225,48,52,116,47,160,88,195,193,70,159,100,44,177,185,51,
        58,58,25,146,254,62,78,227,20,78,226,4,210,201,254,83,137,243,63,79,40,99,14,1,207,241,8,111,112,
        144,176,82,83,171,53,60,132,95,210,102,155,200,201,234,57,35,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/refresh.png
    const unsigned char refresh_png[685] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        103,65,77,65,0,0,175,200,55,5,138,233,0,0,0,25,116,69,88,116,83,111,102,116,119,97,114,101,0,65,
        100,111,98,101,32,73,109,97,103,101,82,101,97,100,121,113,201,101,60,0,0,2,63,73,68,65,84,56,203,
        141,147,219,75,211,97,28,198,7,251,51,98,118,208,146,66,186,176,66,214,57,203,100,45,79,100,6,173,
        54,95,215,116,228,161,129,101,206,197,154,254,220,220,161,29,220,73,205,177,97,73,70,37,252,192,
        104,132,101,181,141,13,215,97,249,35,232,218,59,17,188,13,239,158,190,27,93,56,253,97,187,120,111,
        222,195,243,60,239,243,225,43,1,32,249,223,186,241,188,113,176,101,90,33,21,59,147,148,34,208,52,
        85,47,40,198,47,68,118,21,232,251,172,149,221,93,212,24,116,111,85,113,205,124,219,250,205,23,205,
        184,22,85,162,33,92,7,253,203,118,116,60,83,225,164,249,184,79,84,160,119,169,67,174,127,175,230,
        185,164,17,254,172,3,145,159,65,68,87,66,152,202,249,16,252,250,4,222,229,49,140,165,44,104,13,53,
        162,170,183,114,180,72,160,231,67,187,172,235,221,45,222,179,108,197,236,175,105,76,254,240,226,
        105,206,143,208,55,55,124,89,59,92,105,14,214,148,25,143,191,24,113,213,93,143,131,186,3,206,34,
        1,138,108,48,127,122,128,25,97,18,145,92,16,238,140,13,186,57,53,206,219,228,249,200,56,54,112,20,
        77,62,5,174,184,234,80,161,221,23,216,241,5,245,235,214,184,35,105,41,56,58,83,28,46,185,206,172,
        158,229,106,220,91,47,85,118,150,11,229,108,111,76,180,196,235,51,13,107,212,242,38,181,252,167,
        214,126,106,227,180,229,4,183,253,210,126,77,153,169,76,181,71,74,102,140,144,50,66,202,148,129,
        139,140,204,152,132,90,102,151,61,231,24,69,102,20,153,81,100,214,159,238,146,26,18,119,76,219,133,
        200,140,35,179,141,127,102,155,100,182,38,202,157,144,198,8,169,176,117,143,144,186,201,108,213,
        147,182,17,21,59,6,22,238,229,251,137,239,120,76,72,3,214,140,9,195,137,135,160,200,160,200,160,
        200,232,126,163,133,43,201,21,144,58,210,35,104,155,104,206,35,53,20,61,38,164,78,46,101,196,220,
        239,104,1,105,76,152,40,66,58,146,24,42,32,213,206,222,198,145,238,67,60,33,149,21,9,16,210,209,
        71,31,251,17,91,9,23,144,134,191,123,49,158,117,194,149,177,98,120,105,8,61,243,58,180,248,149,56,
        172,175,224,9,169,92,116,22,40,178,175,143,239,132,254,21,203,35,5,33,69,141,169,26,213,247,171,
        214,41,114,156,144,26,8,169,108,215,97,202,15,14,181,44,148,50,104,162,155,132,84,74,72,7,75,17,
        248,11,132,172,136,153,232,234,140,40,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/sender_ico.png
    const unsigned char sender_ico_png[1010] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,2,0,0,0,252,24,237,163,0,0,0,3,
        115,66,73,84,8,8,8,219,225,79,224,0,0,0,9,112,72,89,115,0,0,14,116,0,0,14,116,1,107,36,179,214,0,
        0,3,149,73,68,65,84,72,199,237,86,77,79,27,87,20,61,247,49,99,140,153,196,56,198,31,96,7,145,64,
        138,170,102,213,132,166,105,210,143,5,217,52,82,179,35,120,195,134,127,208,32,126,65,66,179,67,100,
        17,80,112,89,164,82,45,132,132,2,138,133,187,97,145,74,169,28,33,33,21,42,225,132,20,112,226,216,
        78,9,96,20,7,219,51,243,110,23,83,82,74,168,129,74,89,84,226,174,158,52,231,232,188,123,207,189,
        247,13,49,51,222,103,8,188,231,56,20,248,255,8,104,90,53,237,22,93,93,93,229,137,202,62,5,102,103,
        231,114,185,92,32,16,108,108,108,240,249,253,193,96,48,242,99,36,155,205,6,131,193,242,68,58,232,
        28,16,209,201,166,147,21,66,60,126,252,100,95,4,62,96,204,204,204,28,136,117,96,147,61,30,79,91,
        91,219,254,241,59,61,80,85,229,236,217,214,66,161,240,119,138,96,231,17,231,131,159,31,100,179,217,
        137,137,137,154,26,167,219,237,158,251,109,110,112,112,176,170,170,138,0,102,48,152,64,12,206,231,
        95,15,220,30,44,87,162,250,64,253,174,153,158,59,247,73,83,115,147,97,232,94,175,239,202,149,111,
        118,92,203,235,173,85,84,69,173,84,1,196,227,241,237,196,157,2,62,159,119,87,1,71,181,227,225,47,
        15,173,11,109,191,150,148,242,249,179,231,205,31,52,79,198,98,177,216,100,203,135,45,211,211,211,
        229,61,32,0,23,63,191,216,218,218,218,219,219,187,184,248,251,213,142,171,169,84,234,82,219,165,
        244,139,116,119,119,247,232,232,168,133,187,249,221,77,119,237,49,34,114,29,115,61,125,178,16,30,
        186,115,103,104,104,121,113,73,8,81,206,3,69,169,0,112,230,227,51,253,253,253,61,61,61,29,161,208,
        229,175,47,135,66,161,104,52,42,165,180,217,108,249,124,222,66,222,155,184,247,106,101,21,64,177,
        88,108,106,110,254,246,218,53,65,98,126,126,222,52,205,114,147,108,74,6,48,54,54,214,217,217,89,
        44,20,127,184,123,247,251,112,88,59,122,164,175,175,175,84,42,21,139,197,183,200,76,58,211,209,209,
        1,64,8,177,182,190,246,211,100,44,26,141,230,114,185,61,50,96,41,1,36,18,137,66,161,96,24,134,215,
        235,141,63,122,228,247,251,227,241,184,199,227,49,12,227,45,114,105,105,201,58,56,157,206,205,252,
        155,245,141,28,51,10,133,77,34,42,187,42,136,0,132,195,97,151,203,197,204,134,97,168,170,42,165,
        41,37,107,154,102,179,169,166,41,1,52,52,28,47,233,186,32,2,67,55,117,119,173,251,86,255,45,203,
        193,61,50,0,164,53,13,138,162,48,75,69,81,136,104,101,101,125,179,176,169,235,58,32,24,38,0,170,
        168,176,129,153,4,129,201,16,154,67,179,186,171,174,174,190,84,42,149,19,32,8,0,215,111,220,56,209,
        120,130,153,137,104,57,153,124,150,76,90,95,19,137,132,97,24,23,46,124,230,243,250,216,90,99,68,
        36,165,97,152,31,157,62,77,196,199,131,1,151,203,85,78,64,178,4,48,53,53,85,237,112,48,131,8,111,
        242,155,219,1,186,174,127,249,197,87,14,205,193,12,2,24,108,117,246,167,231,207,131,176,182,186,
        102,175,178,151,219,166,254,58,127,38,157,9,133,66,71,157,78,107,40,54,54,54,134,135,135,237,118,
        59,128,145,145,17,33,68,123,123,123,32,24,96,211,100,1,48,136,193,68,96,22,162,34,149,74,101,50,
        105,159,207,255,239,37,34,2,16,137,68,118,221,92,170,170,90,109,174,85,107,146,13,102,34,134,180,
        202,74,72,38,147,239,46,255,157,2,153,116,102,121,105,249,229,31,47,9,224,109,157,197,76,118,187,
        109,246,215,217,83,45,167,0,44,60,93,144,82,2,127,45,57,171,78,44,121,239,7,103,124,124,252,126,
        244,126,165,173,18,180,85,93,108,241,153,165,148,3,183,7,86,87,95,41,138,186,165,207,0,129,88,154,
        178,230,159,246,254,199,23,237,240,183,229,80,224,157,248,19,117,226,90,179,160,85,102,127,0,0,0,
        0,73,69,78,68,174,66,96,130
    };
    // resources/settings-icon16.png
    const unsigned char settings_icon16_png[625] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,2,56,
        73,68,65,84,120,218,125,83,59,107,98,81,16,158,235,51,42,62,241,81,40,168,40,166,176,240,130,6,76,
        19,100,171,128,63,192,194,194,34,36,89,180,136,191,64,75,65,4,9,22,121,17,19,132,116,254,128,104,
        177,72,42,11,3,11,10,162,149,226,3,132,20,130,26,117,125,237,156,203,70,244,70,119,154,115,57,115,
        231,155,153,239,251,14,5,172,48,26,141,180,86,171,189,60,56,56,248,65,81,148,137,220,173,86,171,
        198,116,58,253,213,235,245,238,154,205,230,239,205,255,169,175,15,185,92,46,178,217,108,215,98,177,
        248,140,199,227,113,48,182,128,151,203,37,204,231,243,229,120,60,126,172,215,235,87,253,126,127,
        188,6,144,201,100,34,187,221,254,138,93,79,184,92,46,252,47,22,139,5,76,38,147,183,106,181,122,74,
        64,24,0,167,211,121,47,149,74,207,119,21,155,76,38,240,251,253,144,76,38,225,243,243,115,13,50,28,
        14,31,74,165,210,5,165,215,235,105,179,217,252,206,231,243,57,187,58,166,82,41,40,22,139,240,242,
        242,2,30,143,7,10,133,2,115,63,155,205,150,141,70,195,73,57,28,142,27,92,225,39,123,231,175,200,
        100,50,160,211,233,32,159,207,131,197,98,129,96,48,184,230,100,48,24,220,82,71,71,71,53,220,221,
        134,140,127,43,62,62,62,134,88,44,70,84,128,86,171,5,241,120,28,42,149,10,252,83,134,112,81,167,
        92,46,215,84,40,20,10,216,0,42,149,10,158,159,159,65,169,84,66,58,157,134,167,167,167,173,60,1,64,
        105,255,80,72,32,3,176,165,45,130,37,18,9,112,187,221,80,46,151,33,20,10,49,196,177,131,1,160,105,
        154,89,97,51,225,243,249,32,28,14,19,166,33,16,8,64,183,219,221,201,15,179,194,225,225,225,22,137,
        86,171,149,25,89,32,16,64,52,26,133,92,46,183,179,152,144,136,13,110,41,141,70,67,27,12,134,119,
        226,62,146,32,29,209,32,196,27,16,137,68,246,26,138,184,178,211,233,56,25,230,112,138,123,137,68,
        114,78,166,240,122,189,160,86,171,33,155,205,194,104,52,218,219,29,115,15,181,90,237,130,1,64,255,
        139,208,113,175,72,230,201,62,63,108,22,35,121,111,104,162,83,116,230,120,173,157,8,3,87,185,198,
        227,12,45,205,97,203,74,100,67,37,150,72,220,99,187,221,190,34,197,140,98,236,14,56,62,173,80,40,
        46,113,154,111,207,25,185,185,251,248,248,216,122,206,127,1,253,92,2,87,157,249,161,218,0,0,0,0,
        73,69,78,68,174,66,96,130
    };
    // resources/text_letter_omega.png
    const unsigned char text_letter_omega_png[541] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        103,65,77,65,0,0,175,200,55,5,138,233,0,0,0,25,116,69,88,116,83,111,102,116,119,97,114,101,0,65,
        100,111,98,101,32,73,109,97,103,101,82,101,97,100,121,113,201,101,60,0,0,1,175,73,68,65,84,56,203,
        197,147,219,74,2,81,24,133,125,4,31,161,251,40,164,186,137,136,38,40,40,233,64,103,42,210,78,80,
        84,164,72,18,33,49,70,102,7,44,20,52,59,80,27,162,140,10,178,19,93,89,243,8,3,82,97,67,77,58,131,
        51,204,72,238,71,248,219,93,104,208,140,221,20,116,177,110,54,123,125,123,255,107,241,27,0,192,240,
        27,25,254,28,208,27,18,139,198,246,36,228,185,80,223,92,167,10,59,119,162,176,243,103,234,91,95,
        72,68,173,43,169,162,31,1,189,65,209,228,187,205,224,181,155,12,238,244,11,84,238,156,24,41,247,
        185,138,233,51,5,155,23,120,147,46,160,39,40,24,125,196,24,142,101,161,115,227,203,156,147,121,145,
        167,8,24,102,143,101,92,231,122,49,106,0,93,126,193,190,203,96,112,70,20,182,208,188,195,219,34,
        187,122,173,2,229,228,236,26,192,244,129,204,236,220,103,129,124,151,46,4,168,157,229,104,239,165,
        10,237,107,73,70,3,152,64,18,19,190,203,66,147,135,47,8,168,118,112,244,98,84,37,143,232,0,186,252,
        41,20,142,189,67,119,64,136,22,2,152,221,175,81,79,84,249,28,1,105,0,141,110,158,90,190,202,192,
        76,68,198,63,100,128,29,135,18,148,141,62,82,186,53,54,47,241,104,233,66,129,154,25,110,240,187,
        185,98,236,105,208,121,36,67,181,253,25,233,214,216,29,72,49,196,104,106,112,243,104,124,63,141,
        43,167,18,249,170,202,71,159,140,253,33,1,87,217,18,168,212,250,96,170,119,113,218,12,156,17,25,
        170,236,207,116,229,116,130,234,88,79,178,109,190,100,190,206,22,47,207,146,112,217,18,75,156,42,
        30,136,211,214,77,17,52,0,199,145,4,182,3,9,166,80,26,38,137,198,247,210,249,75,35,219,34,12,17,
        89,183,68,176,16,243,128,30,224,223,182,241,3,60,110,211,27,108,60,229,235,0,0,0,0,73,69,78,68,174,
        66,96,130
    };
    // resources/text_list_numbers.png
    const unsigned char text_list_numbers_png[357] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,16,0,0,0,16,8,6,0,0,0,31,243,255,97,0,0,0,4,
        103,65,77,65,0,0,175,200,55,5,138,233,0,0,0,25,116,69,88,116,83,111,102,116,119,97,114,101,0,65,
        100,111,98,101,32,73,109,97,103,101,82,101,97,100,121,113,201,101,60,0,0,0,247,73,68,65,84,56,203,
        99,248,255,255,63,3,37,24,76,228,204,127,172,178,232,240,187,255,100,27,0,210,76,145,1,48,67,96,
        236,242,242,242,108,32,254,95,82,82,242,191,160,160,224,127,118,118,246,255,212,212,212,255,9,9,
        9,255,35,35,35,255,7,7,7,255,199,234,130,69,7,73,119,5,3,85,2,113,238,254,183,255,103,237,121,253,
        63,98,226,61,21,178,93,16,218,123,79,165,119,203,75,242,188,16,212,117,71,165,115,211,115,184,230,
        184,184,184,236,136,136,136,255,129,129,129,255,189,188,188,254,59,59,59,255,183,177,177,249,111,
        98,98,242,95,87,87,247,191,154,154,26,106,32,182,173,127,254,191,113,205,211,255,53,171,158,14,80,
        32,150,47,123,252,191,116,233,227,255,197,139,31,147,239,2,144,102,235,188,75,228,199,2,72,51,204,
        5,70,70,70,217,218,218,218,255,85,84,84,254,203,201,201,253,23,23,23,255,47,36,36,244,159,135,135,
        231,63,59,59,251,127,102,102,102,212,64,4,105,4,97,187,162,43,29,116,15,68,0,247,127,213,180,109,
        47,23,45,0,0,0,0,73,69,78,68,174,66,96,130
    };
    // resources/wand.png
    const unsigned char wand_png[1977] {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,6,0,0,0,115,122,122,244,0,0,7,
        128,73,68,65,84,88,133,189,151,123,140,92,85,29,199,63,231,190,231,209,217,199,236,163,110,151,22,
        23,42,165,82,164,242,84,155,66,73,53,54,86,17,172,143,24,124,196,63,140,53,38,36,252,97,12,209,18,
        138,26,19,49,68,131,137,137,104,76,19,35,165,168,33,173,37,65,161,24,64,1,107,27,236,35,133,45,45,
        221,157,238,238,236,99,222,51,119,238,189,231,225,31,187,133,133,237,118,219,248,248,38,191,156,
        201,189,51,247,251,153,239,57,247,228,252,132,49,134,243,75,204,14,26,176,128,54,240,115,224,65,
        64,164,96,195,6,184,241,70,139,210,89,248,195,74,205,104,22,120,194,129,43,52,220,3,92,175,193,181,
        230,158,176,80,115,182,206,34,238,11,165,1,137,133,1,34,173,73,140,133,192,65,89,96,39,22,172,2,
        190,97,97,69,96,36,24,41,89,239,26,134,16,252,30,179,24,200,197,3,216,192,123,176,248,0,14,113,96,
        49,224,66,25,143,210,128,197,96,191,69,174,219,166,121,133,69,203,133,56,109,40,205,196,28,238,147,
        28,246,36,48,91,6,16,239,4,89,26,64,204,177,43,44,214,9,135,175,167,28,234,253,14,85,223,167,144,
        4,208,227,235,229,25,199,44,75,28,107,90,88,194,205,10,252,192,34,76,234,124,69,231,248,4,157,180,
        120,141,99,84,16,212,47,61,1,1,180,176,40,224,224,165,61,110,238,77,81,236,202,50,204,50,162,102,
        22,59,72,203,170,155,86,173,76,202,23,203,132,112,132,49,229,36,52,94,186,105,229,220,85,123,71,
        247,222,49,101,79,221,20,101,162,31,108,103,251,35,188,107,42,172,37,1,192,65,227,209,38,77,98,119,
        160,50,189,224,172,48,217,104,72,245,52,174,54,29,173,117,118,38,190,206,14,226,245,198,107,173,
        199,105,175,211,174,90,43,125,123,213,126,255,169,45,178,95,110,29,92,53,216,119,240,196,193,159,
        222,187,229,222,149,151,146,128,53,87,142,241,241,84,222,206,136,138,232,178,26,113,191,209,73,191,
        242,226,229,184,241,114,17,152,110,210,100,201,40,223,116,122,150,118,51,137,14,41,189,244,165,227,
        31,117,55,248,183,165,156,12,251,246,237,67,8,65,54,206,46,120,229,46,106,17,106,97,57,145,235,167,
        177,220,46,135,100,185,241,244,144,179,118,96,141,232,239,239,147,135,132,47,91,113,202,248,137,
        147,94,123,75,86,84,83,201,43,215,61,101,57,119,118,172,78,185,46,143,61,246,24,97,24,98,79,219,
        15,239,124,102,231,204,165,0,204,238,0,49,14,53,50,166,105,229,140,109,247,38,190,53,152,36,201,
        224,178,94,255,189,118,111,103,127,237,232,148,73,188,200,19,65,219,78,138,47,232,215,47,23,93,250,
        99,29,93,221,221,221,236,218,181,139,48,12,73,189,153,250,213,15,159,250,254,195,96,48,8,107,222,
        14,179,196,20,24,60,29,226,37,53,19,200,88,101,140,109,117,26,203,203,39,194,238,153,57,54,226,170,
        82,195,50,126,127,166,237,74,219,120,82,188,182,106,196,235,216,124,85,170,167,187,155,199,31,127,
        156,48,12,233,29,238,125,242,155,7,182,255,178,76,67,135,248,186,23,97,101,47,18,0,192,73,28,156,
        154,99,251,177,74,165,72,156,180,145,34,155,8,107,89,187,153,164,100,91,249,42,138,29,29,100,221,
        39,11,71,157,112,176,203,187,203,94,203,238,221,187,105,181,90,228,135,251,95,252,228,241,47,239,
        110,184,42,170,33,116,89,9,186,102,247,132,139,154,2,16,96,5,235,93,25,76,56,249,222,79,175,41,156,
        121,62,104,38,110,208,142,83,94,164,210,94,164,3,39,50,174,253,204,171,195,222,211,71,142,56,226,
        168,160,56,57,73,190,39,79,199,248,224,241,141,246,103,254,214,92,173,245,216,105,29,165,235,126,
        114,67,25,153,91,16,243,34,170,84,160,82,22,148,166,78,38,81,171,87,5,193,80,78,123,43,220,98,152,
        85,19,237,156,246,87,14,57,107,55,111,240,254,248,82,193,251,203,193,99,14,64,185,92,230,192,115,
        7,56,115,162,92,118,229,205,175,216,215,247,101,122,183,245,95,118,164,51,106,171,0,185,12,161,139,
        54,20,236,139,72,224,217,103,103,199,108,160,117,87,190,20,21,171,79,188,212,50,249,107,198,195,
        206,184,217,202,69,165,169,108,252,196,159,142,185,7,255,49,236,105,173,169,84,42,0,172,184,242,
        182,138,59,184,237,232,191,218,173,176,60,243,230,232,234,108,254,244,153,190,201,104,114,66,180,
        255,108,183,229,152,243,79,90,120,236,97,203,133,1,14,31,6,219,50,250,202,85,41,227,101,58,228,88,
        100,53,199,218,206,84,43,234,93,94,107,166,155,39,246,13,103,10,7,135,131,249,230,157,235,54,55,
        244,53,119,77,156,76,68,195,216,162,246,122,115,252,236,129,87,79,143,68,20,213,136,59,172,235,106,
        63,168,61,64,10,104,93,24,96,235,86,52,88,178,212,200,240,226,200,251,154,21,167,171,22,59,65,181,
        214,202,205,140,60,115,114,115,229,216,169,1,173,53,165,82,9,128,220,198,47,182,212,181,119,76,21,
        75,149,134,118,169,27,161,155,202,17,77,148,223,172,230,186,195,48,245,91,13,123,45,24,208,243,215,
        225,162,0,249,60,36,74,200,19,213,172,62,17,247,123,74,118,133,74,122,181,137,167,143,124,36,60,
        51,250,65,165,20,51,51,179,251,138,247,161,109,21,231,11,15,53,107,133,55,195,202,116,173,4,102,
        70,187,98,234,107,159,221,112,249,244,169,233,55,126,119,204,147,212,158,131,147,17,48,246,14,159,
        69,1,238,190,27,52,6,57,20,235,203,62,135,20,73,174,93,250,205,11,159,79,74,51,159,82,74,49,61,61,
        141,49,6,185,230,214,83,141,171,182,140,206,28,250,43,70,216,245,54,214,4,90,140,166,178,222,148,
        103,34,47,180,172,42,91,251,36,27,183,106,204,97,205,104,1,130,96,105,128,151,95,6,4,210,106,249,
        222,232,141,3,242,234,253,7,190,165,195,230,118,165,20,147,147,147,24,99,72,46,191,233,197,198,13,
        95,61,146,36,248,38,9,19,141,169,226,152,25,140,51,218,136,218,227,63,217,243,194,52,88,37,170,123,
        37,106,66,211,157,7,173,193,182,151,6,0,192,22,232,40,137,175,217,123,224,62,37,229,119,148,82,20,
        139,69,140,49,196,61,87,238,169,223,114,207,211,74,203,180,178,148,11,34,65,82,69,71,21,82,246,4,
        4,147,36,153,58,175,190,30,243,232,67,16,157,4,219,1,169,96,222,49,240,2,0,46,104,139,77,43,6,118,
        104,173,239,215,90,51,49,49,129,214,26,153,233,124,100,230,195,223,254,53,53,147,49,126,236,227,
        105,16,174,166,109,66,90,162,65,61,85,197,109,215,57,222,21,115,232,253,49,81,118,246,12,160,229,
        2,151,11,2,108,186,245,230,29,192,3,90,107,198,199,199,209,90,163,133,255,163,226,166,251,126,76,
        84,113,169,199,1,182,246,232,234,212,216,66,19,182,53,61,107,66,110,241,91,60,247,168,228,249,64,
        194,54,125,161,99,199,162,119,54,109,122,219,124,108,108,108,214,92,243,224,88,229,208,247,120,254,
        218,6,13,171,206,192,27,85,148,154,162,220,156,98,226,108,17,213,57,197,208,85,37,62,158,107,209,
        56,26,195,136,68,196,64,120,105,0,183,223,126,251,14,224,1,128,177,177,49,140,49,104,173,119,22,
        10,103,118,80,207,74,78,174,150,36,233,54,131,141,6,90,214,248,251,207,218,188,182,191,141,223,221,
        34,64,162,140,166,222,214,208,13,196,204,158,233,207,47,241,238,190,96,190,249,217,179,103,81,74,
        161,148,218,121,250,244,233,251,23,125,202,127,160,183,0,132,16,108,220,184,177,207,182,237,226,
        185,127,174,181,70,41,245,224,169,83,167,30,56,207,111,205,34,159,23,92,91,188,249,121,215,34,172,
        84,42,157,249,124,254,173,216,163,40,250,197,200,200,200,30,96,237,188,175,169,185,146,64,50,111,
        60,119,237,220,125,61,87,70,8,161,103,57,22,130,204,79,192,2,86,14,13,13,125,215,182,237,59,195,
        48,124,182,80,40,236,62,15,116,2,68,204,78,236,252,138,230,42,158,7,246,14,152,243,17,204,7,16,64,
        6,88,1,184,188,213,28,46,144,230,92,167,243,182,209,252,20,22,36,112,110,92,42,1,230,76,207,213,
        82,250,175,172,129,5,111,193,255,91,23,211,25,253,79,245,111,169,92,3,123,225,137,77,190,0,0,0,0,
        73,69,78,68,174,66,96,130
    };

}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
