///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/clrpicker.h>
#include <wx/colour.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/settings.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>

class wxOptionsBase : public wxDialog
{
public:
    wxOptionsBase() {}
    wxOptionsBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Opciones",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(485, 433),
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Opciones",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(485, 433),
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void colour_comments(wxColourPickerEvent& event) { event.Skip(); }
    virtual void colour_line(wxColourPickerEvent& event) { event.Skip(); }
    virtual void colour_m(wxColourPickerEvent& event) { event.Skip(); }
    virtual void colour_text(wxColourPickerEvent& event) { event.Skip(); }
    virtual void colour_textCtrl(wxColourPickerEvent& event) { event.Skip(); }
    virtual void colour_tool(wxColourPickerEvent& event) { event.Skip(); }
    virtual void maximize(wxCommandEvent& event) { event.Skip(); }
    virtual void remove_m08(wxCommandEvent& event) { event.Skip(); }
    virtual void reset_defaults(wxCommandEvent& event) { event.Skip(); }
    virtual void save(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxButton* m_button4;
    wxButton* reset;
    wxCheckBox* m_maximize;
    wxCheckBox* m_remove_m08;
    wxColourPickerCtrl* m_colour_comments;
    wxColourPickerCtrl* m_colour_line;
    wxColourPickerCtrl* m_colour_m;
    wxColourPickerCtrl* m_colour_text;
    wxColourPickerCtrl* m_colour_textCtrl;
    wxColourPickerCtrl* m_colour_tool;
    wxStaticText* m_staticText18;
    wxStaticText* m_staticText19;
    wxStaticText* m_staticText1;
    wxStaticText* m_staticText20;
    wxStaticText* m_staticText21;
    wxStaticText* m_staticText23;
    wxStaticText* m_staticText2;
    wxStaticText* m_staticText3;
    wxStaticText* m_staticText9;
    wxTextCtrl* m_replace_from;
    wxTextCtrl* m_replace_to;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
