///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

// Imported from C:\Users\cbottazzi\Desktop\axia-traductor\wxfb_project.wxui

#include <wx/sizer.h>
#include <wx/statbox.h>

#include "wxParameters_base.h"

bool wxParameters::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto* bSizer2 = new wxBoxSizer(wxVERTICAL);

    auto* sbSizer1 = new wxStaticBoxSizer(wxVERTICAL, this, wxString::FromUTF8("Opciones de código"));

    auto* gSizer2 = new wxGridSizer(2, 0, 0);

    m_staticText1 = new wxStaticText(sbSizer1->GetStaticBox(), wxID_ANY, "Reemplazar sentido de giro");
    gSizer2->Add(m_staticText1, wxSizerFlags().Border(wxALL));

    auto* gSizer3 = new wxGridSizer(3, 0, 0);

    m_replace_from = new wxTextCtrl(sbSizer1->GetStaticBox(), wxID_ANY, wxEmptyString);
    gSizer3->Add(m_replace_from, wxSizerFlags(1).Expand().Border(wxALL));

    m_staticText3 = new wxStaticText(sbSizer1->GetStaticBox(), wxID_ANY, "por");
    gSizer3->Add(m_staticText3, wxSizerFlags().CenterHorizontal().Border(wxALL));

    m_replace_to = new wxTextCtrl(sbSizer1->GetStaticBox(), wxID_ANY, wxEmptyString);
    gSizer3->Add(m_replace_to, wxSizerFlags(1).Expand().Border(wxALL));

    gSizer2->Add(gSizer3, wxSizerFlags(1).Expand());

    m_staticText2 = new wxStaticText(sbSizer1->GetStaticBox(), wxID_ANY, "Opciones ");
    gSizer2->Add(m_staticText2, wxSizerFlags().Border(wxALL));

    m_remove_m08 = new wxCheckBox(sbSizer1->GetStaticBox(), wxID_ANY,
        wxString::FromUTF8("Quitar parámetro M08"));
    gSizer2->Add(m_remove_m08, wxSizerFlags(1).Expand().Border(wxALL));

    sbSizer1->Add(gSizer2, wxSizerFlags(1).Expand().Border(wxALL));

    bSizer2->Add(sbSizer1, wxSizerFlags().Expand().Border(wxALL));

    auto* sbSizer2 = new wxStaticBoxSizer(wxVERTICAL, this, "Colores y opciones de editor");

    auto* gSizer6 = new wxGridSizer(2, 0, 0);

    m_staticText9 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY,
        wxString::FromUTF8("Color de fondo de área de texto"));
    gSizer6->Add(m_staticText9, wxSizerFlags().Border(wxALL));

    m_colour_textCtrl = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, wxColour("#001E3C"));
    gSizer6->Add(m_colour_textCtrl, wxSizerFlags().Right().Border(wxALL));

    m_staticText18 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY, "Color de texto");
    gSizer6->Add(m_staticText18, wxSizerFlags().Border(wxALL));

    m_colour_text = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, *wxBLACK);
    gSizer6->Add(m_colour_text, wxSizerFlags().Right().Border(wxALL));

    m_staticText19 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY, "Color de sentencia M");
    gSizer6->Add(m_staticText19, wxSizerFlags().Border(wxALL));

    m_colour_m = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, *wxBLACK);
    gSizer6->Add(m_colour_m, wxSizerFlags().Right().Border(wxALL));

    m_staticText20 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY, "Color sentencia de herramienta");
    gSizer6->Add(m_staticText20, wxSizerFlags().Border(wxALL));

    m_colour_tool = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, *wxBLACK);
    gSizer6->Add(m_colour_tool, wxSizerFlags().Right().Border(wxALL));

    m_staticText21 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY, "Comentario");
    gSizer6->Add(m_staticText21, wxSizerFlags().Border(wxALL));

    m_colour_comments = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, *wxBLACK);
    gSizer6->Add(m_colour_comments, wxSizerFlags().Right().Border(wxALL));

    m_staticText23 = new wxStaticText(sbSizer2->GetStaticBox(), wxID_ANY,
        wxString::FromUTF8("Color marcador de Número de línea"));
    gSizer6->Add(m_staticText23, wxSizerFlags().Border(wxALL));

    m_colour_line = new wxColourPickerCtrl(sbSizer2->GetStaticBox(), wxID_ANY, *wxBLACK);
    gSizer6->Add(m_colour_line, wxSizerFlags().Right().Border(wxALL));

    m_maximize = new wxCheckBox(sbSizer2->GetStaticBox(), wxID_ANY, "Iniciar ventana maximizada");
    gSizer6->Add(m_maximize, wxSizerFlags().Border(wxALL));

    reset = new wxButton(sbSizer2->GetStaticBox(), wxID_ANY, "Reestablecer");
    gSizer6->Add(reset, wxSizerFlags().Right().Border(wxALL));

    sbSizer2->Add(gSizer6, wxSizerFlags(1).Expand());

    bSizer2->Add(sbSizer2, wxSizerFlags(1).Expand().Border(wxLEFT|wxRIGHT, wxSizerFlags::GetDefaultBorder()));

    m_button4 = new wxButton(this, wxID_ANY, "Guardar");
    bSizer2->Add(m_button4, wxSizerFlags().Right().Border(wxALL));

    SetSizer(bSizer2);
    Centre(wxBOTH);

    // Event handlers
    reset->Bind(wxEVT_BUTTON, &wxParameters::reset_defaults, this);
    m_button4->Bind(wxEVT_BUTTON, &wxParameters::save, this);
    m_maximize->Bind(wxEVT_CHECKBOX, &wxParameters::maximize, this);
    m_remove_m08->Bind(wxEVT_CHECKBOX, &wxParameters::remove_m08, this);
    m_colour_comments->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_comments, this);
    m_colour_line->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_line, this);
    m_colour_m->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_m, this);
    m_colour_text->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_text, this);
    m_colour_textCtrl->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_textCtrl, this);
    m_colour_tool->Bind(wxEVT_COLOURPICKER_CHANGED, &wxParameters::colour_tool, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
