///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

// Imported from C:\Users\cbottazzi\Desktop\axia-traductor\wxfb_project.wxui

#include <wx/sizer.h>

#include "wxSearchBase.h"

#include <wx/mstream.h>  // memory stream classes

// Convert a data array into a wxImage
#ifdef __cpp_inline_variables
inline wxImage wxueImage(const unsigned char* data, size_t size_data)
#else
static wxImage wxueImage(const unsigned char* data, size_t size_data)
#endif
{
    wxMemoryInputStream strm(data, size_data);
    wxImage image;
    image.LoadFile(strm);
    return image;
};

namespace wxue_img
{
    extern const unsigned char magnifier_png[578];  // resources/magnifier.png
}

bool wxSearchBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;
    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);

    auto* bSizer3 = new wxBoxSizer(wxVERTICAL);

    m_staticText5 = new wxStaticText(this, wxID_ANY, "Buscar");
    bSizer3->Add(m_staticText5, wxSizerFlags().Border(wxALL));

    search_term = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_PROCESS_ENTER);
    bSizer3->Add(search_term, wxSizerFlags().Expand().Border(wxALL));

    hint = new wxStaticText(this, wxID_ANY,
        wxString::FromUTF8("Para buscar una próxima coincidencia, presione F3"));
    bSizer3->Add(hint, wxSizerFlags().Border(wxALL));

    m_button2 = new wxButton(this, wxID_ANY, "Buscar");
        m_button2->SetBitmap(wxBitmapBundle::FromBitmap(wxueImage(wxue_img::magnifier_png, sizeof(wxue_img::magnifier_png))));
    bSizer3->Add(m_button2, wxSizerFlags().Right().Border(wxALL));

    SetSizer(bSizer3);
    Centre(wxBOTH);

    // Event handlers
    m_button2->Bind(wxEVT_BUTTON, &wxSearchBase::search, this);
    Bind(wxEVT_KEY_UP, &wxSearchBase::evt_key_up, this);
    search_term->Bind(wxEVT_KEY_UP, &wxSearchBase::evt_key_up, this);
    search_term->Bind(wxEVT_TEXT_ENTER, &wxSearchBase::search, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
