# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxue_generated_code

    ${CMAKE_CURRENT_LIST_DIR}/wxAboutBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxActualizacionesBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxMainWindowBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxOptionsBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxSearchBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxSearchReplaceBase.cpp

)
