# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxue_generated_code

    ${CMAKE_CURRENT_LIST_DIR}/ComprobarActualizaciones_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/about_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/searchDialog_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/search_and_replace_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxMainWindow_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wxParameters_base.cpp

)
